=== dabralhd/experimental/staiotcraft-json-analysis/clustered_ai-json-files/schema_group_14_86e55c69/detected_schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "uuid": {
      "type": "string"
    },
    "ai_project_name": {
      "type": "string"
    },
    "type": {
      "type": "null"
    },
    "display_name": {
      "type": "null"
    },
    "description": {
      "type": "null"
    },
    "version": {
      "type": "null"
    },
    "schema_version": {
      "type": "null"
    },
    "last_update_time": {
      "type": "string"
    },
    "creation_time": {
      "type": "string"
    },
    "project_owner_uuid": {
      "type": "string"
    },
    "models": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "uuid": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "dataset": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "dataset_id": {
                "type": "string"
              }
            },
            "required": [
              "dataset_id",
              "name"
            ]
          },
          "metadata": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "classes": {
                "type": "null"
              }
            },
            "required": [
              "classes",
              "type"
            ]
          },
          "target": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "component": {
                "type": "string"
              },
              "device": {
                "type": "string"
              }
            },
            "required": [
              "component",
              "device",
              "type"
            ]
          },
          "creation_time": {
            "type": "string"
          },
          "last_update_time": {
            "type": "string"
          },
          "model_owner_uuid": {
            "type": "string"
          }
        },
        "required": [
          "creation_time",
          "dataset",
          "last_update_time",
          "metadata",
          "model_owner_uuid",
          "name",
          "target",
          "uuid"
        ]
      }
    },
    "deployments": {
      "type": "array"
    },
    "applications": {
      "type": "array"
    }
  },
  "required": [
    "ai_project_name",
    "applications",
    "creation_time",
    "deployments",
    "description",
    "display_name",
    "last_update_time",
    "models",
    "project_owner_uuid",
    "schema_version",
    "type",
    "uuid",
    "version"
  ]
}

=== dabralhd/experimental/staiotcraft-json-analysis/processed_schema_workspace/ai_528.json
{"$schema": "/data/artifacts/.assets/schemas/ai_main_schema.json", "schema_version": "v11", "ai_project_name": "iot_test", "display_name": "Smart Asset Tracking", "description": "Classification of package conditions using the MLC to detect stationary orientation (upright or not) or moving and shaking states.\n\nWith this example, you can individually track the state of a physical item, such as a package, to monitor whether it is moving or being shaken too harshly, and whether it is still upright or not. Classification detects even brief events. You can clone and retrain the model to adapt classes to your use case, for example by tailoring the 'shaken' class to particularly strong motion or, conversely, by making it more sensitive for fragile items. To use this example, simply position the board on top of the item, ensuring it is secured firmly.", "type": "industrial", "uuid": "076aa6f0-d0ce-418b-b808-86025310f760", "version": "1.0.0", "creation_time": "2025-10-22 13:28:25.087002", "last_update_time": "2025-10-22 13:28:25.087002", "project_owner_uuid": "af0d582a-eb60-4813-a53b-d03ea5ba52b4", "models": [{"uuid": "2eb01977-743f-4b68-bc4a-47461573bfc7", "name": "smart_asset_tracking", "description": "Model to recognize position and orientation of a tracked item, with an Auto-ML based approach.", "creation_time": "2025-10-22 13:28:25.087016", "last_update_time": "2025-10-22 13:28:25.087018", "model_owner_uuid": "af0d582a-eb60-4813-a53b-d03ea5ba52b4", "metadata": {"type": "classifier", "classes": ["stationary_upright", "stationary_not_upright", "motion", "shaken"]}, "dataset": {"dataset_id": "01k861phbffwj29rqy6tmr49t2", "name": "smart_asset_tracking"}, "target": {"type": "mlc", "component": "lsm6dsv16x", "device": "steval-mkboxpro"}, "data_sufficiency": {"creation_time": null, "last_update_time": null, "runtime": {"type": "job", "jobs": [{"name": "mlctools-ds-job", "version": null, "template_id": null}]}, "configuration": null, "artifacts": ["activities_training.json", "counts.json", "feat_names.json", "kmeans_cluster_labels.json", "lda.onnx", "my_kmeans.json", "my_tree.onnx", "window_size_odr_channels.json"], "reports": []}, "training": {"creation_time": null, "last_update_time": null, "runtime": {"type": "job", "jobs": [{"name": "mlctools-job", "version": null, "template_id": null}]}, "configuration": "configuration.json", "artifacts": ["lsm6dsv16x_mlc.json", "lsm6dsv16x_mlc.h"], "reports": ["report.json"]}, "codegen": null, "building": null}], "applications": [{"uuid": "879a9320-a336-4d71-8c8c-476754ff2b02", "type": "gateway", "device_template_uri": "/e2e_systems/gateway/dtmi/appconfig/gateway/MLC_Gateway-8.expanded.json", "device_template_id": "dtmi:appconfig:gateway:MLC_Gateway;8", "device_manifest_uri": "/e2e_systems/gateway/dtmi/appconfig/gateway/MLC_Gateway-8.1.manifest.arm64v8.json", "image_uri": "/e2e_systems/gateway/images/raspberrypi/staiotcraft_rpi_gateway_1_5_0.img.gz", "module_id": "edgeMLC"}, {"uuid": "61458a86-3718-46fb-b124-f1a8db93f105", "type": "datalogging", "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/FP_SNS_DATALOG2_Datalog2-7.expanded.json", "device_template_id": "dtmi:appconfig:steval_mkboxpro:FP_SNS_DATALOG2_Datalog2;7", "binary_uri": "/bluestsdkv2/bin/steval-mkboxpro/FP-SNS-DATALOG2_Datalog2_3_1_0.bin", "binary_id": 381, "protocol": 2}, {"uuid": "44a66ae2-6071-46ed-8e27-f6fe52c9a682", "type": "inference", "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/FP_SNS_STAIOTCFT_AI_Inertial-1.expanded.json", "device_template_id": "dtmi:appconfig:steval_mkboxpro:FP_SNS_STAIOTCFT_AI_Inertial;1", "binary_uri": "/usb/bin/steval-mkboxpro/FP-SNS-STAIOTCFT_AI_Inertial_AssetTrackingOnMLC_1_0_0.bin", "binary_id": 418, "protocol": 1}, {"uuid": "4b228db3-97cb-42fb-b7d4-1797876adbdf", "type": "inference", "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/AI_SSM-1.expanded.json", "device_template_id": "dtmi:appconfig:steval_mkboxpro:AI_SSM;1", "binary_uri": "/bluestsdkv2/bin/steval-mkboxpro/AI-SSM_1_0_0.bin", "binary_id": 438, "protocol": 0, "bluest_v3_payload": {"device_id": "0x0D", "fw_id": "0x25", "payload_id": "0x0001", "decoding_schema": [{"component": "lsm6dsv16x_mlc", "telemetry": "label_id", "type": "int8"}]}}], "deployments": [{"uuid": "60d48117-765f-470d-9d99-6ab7b35f9d8b", "display_name": "Smart Asset Tracking with SensorTile.box PRO and LSM6DSV16X sensor.", "description": "End-to-end system deployment for Smart Asset Tracking use case on the SensorTile.box PRO using the LSM6DSV16X sensor.", "last_update_time": "2025-10-22 13:35:41.237392", "last_deploy_result": null, "cloud_params": {"type": "azure_iotc", "app_url": null}, "gateway": [{"device_id": "267eae6b-7699-4cd0-8c74-797c601a64bd", "display_name": "gateway_0", "gateway_id": null, "description": "Gateway device at position 0.", "application": "879a9320-a336-4d71-8c8c-476754ff2b02", "wifi_mode": "off"}], "leaf": [{"device_id": "09e10d0c-be07-4de4-8db8-7e173212e363", "display_name": "leaf_0", "gateway_id": "gateway_0", "description": "Leaf device at position 0.", "datalogging": {"supported_applications": ["61458a86-3718-46fb-b124-f1a8db93f105"], "application": "61458a86-3718-46fb-b124-f1a8db93f105", "firmware_update": false}, "inference": {"supported_applications": ["44a66ae2-6071-46ed-8e27-f6fe52c9a682", "4b228db3-97cb-42fb-b7d4-1797876adbdf"], "application": "4b228db3-97cb-42fb-b7d4-1797876adbdf", "firmware_update": false, "models": [{"model_name_reference": "smart_asset_tracking", "artifact_type": "json", "component_name": "lsm6dsv16x_mlc"}]}}]}]}

=== dabralhd/experimental/staiotcraft-json-analysis/processed_schema_workspace/ai_1370.json
{
    "$schema": "/data/artifacts/.assets/schemas/ai_main_schema.json",
    "schema_version": "v11",
    "ai_project_name": "testM",
    "display_name": "Smart Asset Tracking",
    "description": "Classification of package conditions using the MLC to detect stationary orientation (upright or not) or moving and shaking states.\n\nWith this example, you can individually track the state of a physical item, such as a package, to monitor whether it is moving or being shaken too harshly, and whether it is still upright or not. Classification detects even brief events. You can clone and retrain the model to adapt classes to your use case, for example by tailoring the 'shaken' class to particularly strong motion or, conversely, by making it more sensitive for fragile items. To use this example, simply position the board on top of the item, ensuring it is secured firmly.",
    "type": "industrial",
    "uuid": "646720c4-59f5-4c79-b95a-c8c3a02a9fab",
    "version": "1.0.0",
    "creation_time": "2026-02-20 17:34:24.587287",
    "last_update_time": "2026-02-20 17:34:24.587287",
    "project_owner_uuid": "6030675e-f6ba-4f10-ae9e-64942185c508",
    "models": [
        {
            "uuid": "363d8fbd-19bd-4e37-b639-b9eefc98563a",
            "name": "smart_asset_tracking",
            "description": "Model to recognize position and orientation of a tracked item, with an Auto-ML based approach.",
            "creation_time": "2026-02-20 17:34:24.587299",
            "last_update_time": "2026-02-20 17:34:24.587301",
            "model_owner_uuid": "6030675e-f6ba-4f10-ae9e-64942185c508",
            "metadata": {
                "type": "classifier",
                "classes": [
                    "stationary_upright",
                    "stationary_not_upright",
                    "motion",
                    "shaken"
                ]
            },
            "dataset": {
                "dataset_id": "01khy1vy1xkama9mnwznbn78d1",
                "name": "smart_asset_tracking"
            },
            "target": {
                "type": "mlc",
                "component": "lsm6dsv16x",
                "device": "steval-mkboxpro"
            },
            "data_sufficiency": {
                "creation_time": null,
                "last_update_time": null,
                "runtime": {
                    "type": "job",
                    "jobs": [
                        {
                            "name": "mlctools-ds-job",
                            "version": null,
                            "template_id": null
                        }
                    ]
                },
                "configuration": null,
                "artifacts": [
                    "activities_training.json",
                    "counts.json",
                    "feat_names.json",
                    "kmeans_cluster_labels.json",
                    "lda.onnx",
                    "my_kmeans.json",
                    "my_tree.onnx",
                    "window_size_odr_channels.json"
                ],
                "reports": []
            },
            "training": {
                "creation_time": null,
                "last_update_time": null,
                "runtime": {
                    "type": "job",
                    "jobs": [
                        {
                            "name": "mlctools-job",
                            "version": null,
                            "template_id": null
                        }
                    ]
                },
                "configuration": "configuration.json",
                "artifacts": [
                    "lsm6dsv16x_mlc.json",
                    "lsm6dsv16x_mlc.h"
                ],
                "reports": [
                    "report.json"
                ]
            },
            "codegen": null,
            "building": null
        }
    ],
    "applications": [
        {
            "uuid": "174fa26f-74e0-4bb1-b2b2-888989c5846e",
            "type": "gateway",
            "device_template_uri": "/e2e_systems/gateway/dtmi/appconfig/gateway/MLC_Gateway-8.expanded.json",
            "device_template_id": "dtmi:appconfig:gateway:MLC_Gateway;8",
            "device_manifest_uri": "/e2e_systems/gateway/dtmi/appconfig/gateway/MLC_Gateway-8.1.manifest.arm64v8.json",
            "image_uri": "/e2e_systems/gateway/images/raspberrypi/staiotcraft_rpi_gateway_1_5_0.img.gz",
            "module_id": "edgeMLC"
        },
        {
            "uuid": "c3b343b5-b45d-4ef8-bf05-271dcd0bfd00",
            "type": "datalogging",
            "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/FP_SNS_DATALOG2_Datalog2-7.expanded.json",
            "device_template_id": "dtmi:appconfig:steval_mkboxpro:FP_SNS_DATALOG2_Datalog2;7",
            "binary_uri": "/bluestsdkv2/bin/steval-mkboxpro/FP-SNS-DATALOG2_Datalog2_3_1_0.bin",
            "binary_id": 381,
            "protocol": 2
        },
        {
            "uuid": "28763b68-9ccb-48dd-a112-6ad3222617a4",
            "type": "inference",
            "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/FP_SNS_STAIOTCFT_AI_Inertial-1.expanded.json",
            "device_template_id": "dtmi:appconfig:steval_mkboxpro:FP_SNS_STAIOTCFT_AI_Inertial;1",
            "binary_uri": "/usb/bin/steval-mkboxpro/FP-SNS-STAIOTCFT_AI_Inertial_AssetTrackingOnMLC_1_0_0.bin",
            "binary_id": 418,
            "protocol": 1
        },
        {
            "uuid": "0d71e9a2-9726-460d-98c0-dcb9c2b46837",
            "type": "inference",
            "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/AI_SSM-1.expanded.json",
            "device_template_id": "dtmi:appconfig:steval_mkboxpro:AI_SSM;1",
            "binary_uri": "/bluestsdkv2/bin/steval-mkboxpro/AI-SSM_1_0_0.bin",
            "binary_id": 438,
            "protocol": 0,
            "bluest_v3_payload": {
                "device_id": "0x0D",
                "fw_id": "0x25",
                "payload_id": "0x0001",
                "decoding_schema": [
                    {
                        "component": "lsm6dsv16x_mlc",
                        "telemetry": "label_id",
                        "type": "int8_t"
                    }
                ]
            }
        }
    ],
    "deployments": [
        {
            "uuid": "c4aa1873-e37a-4ca1-8d27-47257e90383c",
            "display_name": "Smart Asset Tracking with SensorTile.box PRO and LSM6DSV16X sensor.",
            "description": "End-to-end system deployment for Smart Asset Tracking use case on the SensorTile.box PRO using the LSM6DSV16X sensor.",
            "last_update_time": "2026-02-18 16:04:28.512693",
            "last_deploy_result": null,
            "cloud_params": {
                "type": "azure_iotc",
                "app_url": null
            },
            "gateway": [
                {
                    "device_id": "d81743df-621b-4cf5-95f4-ff73e02b3df4",
                    "display_name": "gateway_0",
                    "gateway_id": null,
                    "description": "Gateway device at position 0.",
                    "application": "4d3ae34d-cf42-484c-ba5e-4c2d899bed52",
                    "wifi_mode": "off"
                }
            ],
            "leaf": [
                {
                    "device_id": "7b654423-a24d-46cf-bbd0-fb7ca5b6e614",
                    "display_name": "leaf_0",
                    "gateway_id": "d81743df-621b-4cf5-95f4-ff73e02b3df4",
                    "description": "Leaf device at position 0.",
                    "datalogging": {
                        "supported_applications": [
                            "52a74366-40d0-4d20-924b-208277faa565"
                        ],
                        "application": "52a74366-40d0-4d20-924b-208277faa565",
                        "firmware_update": false
                    },
                    "inference": {
                        "supported_applications": [
                            "bd6ed21a-be2e-4e4d-b169-cf0b5e9ea964",
                            "626d8e07-b5e6-4f3e-bc64-275f4753277b"
                        ],
                        "application": "bd6ed21a-be2e-4e4d-b169-cf0b5e9ea964",
                        "firmware_update": false,
                        "models": [
                            {
                                "model_name_reference": "smart_asset_tracking",
                                "artifact_type": "json",
                                "component_name": "lsm6dsv16x_mlc"
                            }
                        ]
                    }
                }
            ]
        }
    ]
}

=== dabralhd/experimental/staiotcraft-json-analysis/ai-json-files/ai_1570.json
{
    "uuid": "afd5dafc-b449-4bc3-9285-92320e2b5438",
    "ai_project_name": "test1",
    "type": null,
    "display_name": null,
    "description": "",
    "version": null,
    "schema_version": null,
    "last_update_time": "2026-06-04 14:02:17.773357",
    "creation_time": "2026-06-04 14:02:16.467864",
    "project_owner_uuid": "1ac3e1ac-2d7f-4d3f-bf0d-84e0fa9ff3d0",
    "models": [
        {
            "uuid": "7d80f842-05c5-4adc-8c27-bcc9d9f8eade",
            "name": "test1",
            "dataset": {
                "name": "dataset1",
                "dataset_id": "01kt9f26dvt07cy08bb0rkxg3t"
            },
            "metadata": {
                "type": "classifier",
                "classes": [
                    "tag1",
                    "tag1b"
                ]
            },
            "target": {
                "type": "mlc",
                "component": "ism330dhcx",
                "device": "steval-stwinbx1"
            },
            "creation_time": "2026-06-04 14:02:17.749048",
            "last_update_time": "2026-06-04 14:02:17.749057",
            "model_owner_uuid": "1ac3e1ac-2d7f-4d3f-bf0d-84e0fa9ff3d0"
        }
    ],
    "deployments": [],
    "applications": []
}

=== dabralhd/experimental/staiotcraft-json-analysis/ai-json-files/ai_510.json
{
    "uuid": "5b5443d0-623e-4120-b553-21517f4e4201",
    "ai_project_name": "SmartAssetTrackingNucleoPj",
    "type": null,
    "display_name": null,
    "description": "",
    "version": null,
    "last_update_time": "2026-06-03 12:11:59.869137",
    "creation_time": "2026-03-27 11:54:38.691251",
    "project_owner_uuid": "363af7b3-752e-40df-855d-a5ebc3801d8e",
    "models": [
        {
            "uuid": "e030d6ec-1ca2-4272-b506-1ebb12371d8d",
            "name": "SmartAssetTrackingModel",
            "dataset": {
                "name": "SmartAssetTracking",
                "dataset_id": "01kmqj3pwc1g1thg67bswvf2fj"
            },
            "metadata": {
                "type": "classifier",
                "classes": [
                    "stationary_upright",
                    "stationary_not_upright",
                    "motion",
                    "shaken"
                ]
            },
            "target": {
                "type": "mlc",
                "component": "ism6hg256x",
                "device": "nucleo-u575zi-q"
            },
            "creation_time": "2026-03-27 11:54:39.944210",
            "last_update_time": "2026-03-27 11:54:39.944216",
            "model_owner_uuid": "363af7b3-752e-40df-855d-a5ebc3801d8e",
            "training": {
                "runtime": {
                    "type": "job",
                    "jobs": [
                        {
                            "name": "mlctools-job",
                            "version": null,
                            "template_id": "01J3QGW4RYFHA34N3Z3WPS97GH"
                        }
                    ]
                },
                "configuration": "configuration.json",
                "reports": [
                    "report.json"
                ],
                "artifacts": [
                    "ism6hg256x_mlc.json",
                    "ism6hg256x_mlc.h"
                ],
                "last_update_time": "2026-03-27 11:54:52.142393",
                "creation_time": "2026-03-27 11:54:52.142391"
            }
        },
        {
            "uuid": "e4cc7777-c637-4e88-a470-5400108e63b3",
            "name": "test-export",
            "dataset": {
                "name": "SmartAssetTracking",
                "dataset_id": "01kmqj3pwc1g1thg67bswvf2fj"
            },
            "metadata": {
                "type": "classifier",
                "classes": [
                    "stationary_upright",
                    "stationary_not_upright",
                    "motion",
                    "shaken"
                ]
            },
            "target": {
                "type": "mlc",
                "component": "ism6hg256x",
                "device": "nucleo-u575zi-q"
            },
            "creation_time": "2026-06-03 11:48:44.414239",
            "last_update_time": "2026-06-03 11:48:44.414251",
            "model_owner_uuid": "6030675e-f6ba-4f10-ae9e-64942185c508",
            "training": {
                "runtime": {
                    "type": "job",
                    "jobs": [
                        {
                            "name": "mlctools-job",
                            "version": null,
                            "template_id": "01J3QGW4RYFHA34N3Z3WPS97GH"
                        }
                    ]
                },
                "configuration": "configuration.json",
                "reports": [
                    "report.json"
                ],
                "artifacts": [
                    "ism6hg256x_mlc.json",
                    "ism6hg256x_mlc.h"
                ],
                "last_update_time": "2026-06-03 12:00:36.194117",
                "creation_time": "2026-06-03 12:00:36.194114"
            }
        },
        {
            "uuid": "06b686a5-ff52-4c3d-97b2-83789656537e",
            "name": "my-model",
            "dataset": {
                "name": "BackpackMonitoring",
                "dataset_id": "01khx9r090ntgvb9f3djp0tz7s"
            },
            "metadata": {
                "type": "classifier",
                "classes": [
                    "backward_leaning",
                    "proper_posture"
                ]
            },
            "target": {
                "type": "mlc",
                "component": "lsm6dsv16x",
                "device": "steval-mkboxpro"
            },
            "creation_time": "2026-06-03 12:11:59.838550",
            "last_update_time": "2026-06-03 12:11:59.838563",
            "model_owner_uuid": "6030675e-f6ba-4f10-ae9e-64942185c508"
        }
    ],
    "deployments": [],
    "applications": [],
    "schema_version": null
}
