=== dabralhd/experimental/staiotcraft-json-analysis/clustered_ai-json-files/schema_group_14_86e55c69/detected_schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "uuid": {
      "type": "string"
    },
    "ai_project_name": {
      "type": "string"
    },
    "type": {
      "type": "null"
    },
    "display_name": {
      "type": "null"
    },
    "description": {
      "type": "null"
    },
    "version": {
      "type": "null"
    },
    "schema_version": {
      "type": "null"
    },
    "last_update_time": {
      "type": "string"
    },
    "creation_time": {
      "type": "string"
    },
    "project_owner_uuid": {
      "type": "string"
    },
    "models": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "uuid": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "dataset": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "dataset_id": {
                "type": "string"
              }
            },
            "required": [
              "dataset_id",
              "name"
            ]
          },
          "metadata": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "classes": {
                "type": "null"
              }
            },
            "required": [
              "classes",
              "type"
            ]
          },
          "target": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "component": {
                "type": "string"
              },
              "device": {
                "type": "string"
              }
            },
            "required": [
              "component",
              "device",
              "type"
            ]
          },
          "creation_time": {
            "type": "string"
          },
          "last_update_time": {
            "type": "string"
          },
          "model_owner_uuid": {
            "type": "string"
          }
        },
        "required": [
          "creation_time",
          "dataset",
          "last_update_time",
          "metadata",
          "model_owner_uuid",
          "name",
          "target",
          "uuid"
        ]
      }
    },
    "deployments": {
      "type": "array"
    },
    "applications": {
      "type": "array"
    }
  },
  "required": [
    "ai_project_name",
    "applications",
    "creation_time",
    "deployments",
    "description",
    "display_name",
    "last_update_time",
    "models",
    "project_owner_uuid",
    "schema_version",
    "type",
    "uuid",
    "version"
  ]
}

=== dabralhd/experimental/staiotcraft-json-analysis/processed_schema_workspace/ai_890.json
{"$schema": "/data/artifacts/.assets/schemas/ai_main_schema.json", "schema_version": "v11", "ai_project_name": "project_name_594615-shared", "display_name": "Tennis Activity Recognition", "description": "Classification of tennis shots using the MLC, including forehand, backhand, slice-forehand, slice-backhand, and serve strokes.\n\nThis example leverages both the accelerometer and the gyroscope sensors to better detect the movements. To use this example effectively, plug the DIL24 extension onto the board and place the board on the outside of the right wrist and secure it firmly. Make sure it is oriented in such a way that the two buttons are facing toward your shoulder, with the LEDs and logos visible and facing outward. In case you need a different placement on the wrist or want to add some more movements of your own, just clone the project into your workspace, collect a new dataset, and retrain the model.", "type": "entertainment", "uuid": "44353616-27b6-444b-85c2-fec189e015ca", "version": "1.0.0", "creation_time": "2026-01-21 09:38:31.209833", "last_update_time": "2026-01-21 09:38:31.209833", "project_owner_uuid": "90ab4947-c200-4776-a316-d02c3041c4b8", "models": [{"uuid": "0a9a7b3c-e3ee-4383-822f-55ced1304545", "name": "tennis_activity_recognition_80x", "description": "Model to recognize tennis shots, with an Auto-ML based approach.", "creation_time": "2026-01-21 09:38:31.209846", "last_update_time": "2026-01-21 09:38:31.209850", "model_owner_uuid": "90ab4947-c200-4776-a316-d02c3041c4b8", "metadata": {"type": "classifier", "classes": ["no_shot", "serve", "backhand_slice", "forehand_slice", "backhand", "forehand"]}, "dataset": {"dataset_id": "01kffypmmg0cdj9xmv53vp2zaa", "name": "tennis_activity_80x"}, "target": {"type": "mlc", "component": "lsm6dsv80x", "device": "steval-mkboxpro"}, "data_sufficiency": null, "training": {"creation_time": null, "last_update_time": null, "runtime": {"type": "job", "jobs": [{"name": "mlctools-job", "version": null, "template_id": null}]}, "configuration": "configuration.json", "artifacts": ["lsm6dsv80x_mlc.json", "lsm6dsv80x_mlc.h"], "reports": ["report.json"]}, "codegen": null, "building": null}, {"uuid": "fabe56ec-22f5-4096-98f7-ca315a0ff1f8", "name": "tennis_activity_recognition_320x", "description": "Model to recognize tennis shots, with an Auto-ML based approach.", "creation_time": "2026-01-21 09:38:31.209848", "last_update_time": "2026-01-21 09:38:31.209852", "model_owner_uuid": "90ab4947-c200-4776-a316-d02c3041c4b8", "metadata": {"type": "classifier", "classes": ["no_shot", "serve", "backhand_slice", "forehand_slice", "backhand", "forehand"]}, "dataset": {"dataset_id": "01kffypp0mr9xa3gx8g2xhymx8", "name": "tennis_activity_320"}, "target": {"type": "mlc", "component": "lsm6dsv320x", "device": "steval-mkboxpro"}, "data_sufficiency": null, "training": {"creation_time": null, "last_update_time": null, "runtime": {"type": "job", "jobs": [{"name": "mlctools-job", "version": null, "template_id": null}]}, "configuration": "configuration.json", "artifacts": ["lsm6dsv320x_mlc.json", "lsm6dsv320x_mlc.h"], "reports": ["report.json"]}, "codegen": null, "building": null}], "applications": [{"uuid": "cfe6a582-8206-4983-9e2b-cec4740c6240", "type": "gateway", "device_template_uri": "/e2e_systems/gateway/dtmi/appconfig/gateway/MLC_Gateway-8.expanded.json", "device_template_id": "dtmi:appconfig:gateway:MLC_Gateway;8", "device_manifest_uri": "/e2e_systems/gateway/dtmi/appconfig/gateway/MLC_Gateway-8.1.manifest.arm64v8.json", "image_uri": "/e2e_systems/gateway/images/raspberrypi/staiotcraft_rpi_gateway_1_5_0.img.gz", "module_id": "edgeMLC"}, {"uuid": "1840a3e3-888c-48b2-92a0-a721fffbd613", "type": "datalogging", "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/FP_SNS_DATALOG2_Datalog2-7.expanded.json", "device_template_id": "dtmi:appconfig:steval_mkboxpro:FP_SNS_DATALOG2_Datalog2;7", "binary_uri": "/bluestsdkv2/bin/steval-mkboxpro/FP-SNS-DATALOG2_Datalog2_3_1_0.bin", "binary_id": 381, "protocol": 2}, {"uuid": "1537b6cf-1794-4fd8-bf54-6b167c1e954d", "type": "inference", "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/FP_SNS_STAIOTCFT_AI_Inertial-1.expanded.json", "device_template_id": "dtmi:appconfig:steval_mkboxpro:FP_SNS_STAIOTCFT_AI_Inertial;1", "binary_uri": "/usb/bin/steval-mkboxpro/FP-SNS-STAIOTCFT_AI_Inertial_AssetTrackingOnMLC_1_0_0.bin", "binary_id": 418, "protocol": 1}, {"uuid": "00c548f2-ffc1-4a70-a26b-1f3b61f3ff49", "type": "inference", "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/AI_SSM-1.expanded.json", "device_template_id": "dtmi:appconfig:steval_mkboxpro:AI_SSM;1", "binary_uri": "/bluestsdkv2/bin/steval-mkboxpro/AI-SSM_1_0_0.bin", "binary_id": 438, "protocol": 0, "bluest_v3_payload": {"device_id": "0x0D", "fw_id": "0x25", "payload_id": "0x0001", "description": "Environmental Monitor", "decoding_schema": [{"component": "lsm6dsv16x_mlc", "telemetry": "label_id", "type": "int8_t"}]}}], "deployments": [{"uuid": "46e31a4e-6757-44cc-b674-d748ba5f52f6", "display_name": "Tennis Activity Recognition with SensorTile.box PRO and LSM6DSV80X sensor.", "description": "End-to-end system deployment for Tennis Activity Recognition use case on the SensorTile.box PRO using the LSM6DSV80X sensor.", "last_update_time": null, "last_deploy_result": null, "cloud_params": {"type": "azure_iotc", "app_url": null}, "gateway": [{"device_id": "gateway_0", "display_name": "gateway_0", "gateway_id": null, "description": "Gateway device at position 0.", "application": "2e3d92ca-c14a-4e9b-b270-50101a6151f9", "wifi_mode": "off"}], "leaf": [{"device_id": "leaf_0", "display_name": "leaf_0", "gateway_id": "gateway_0", "description": "Leaf device at position 0.", "datalogging": {"supported_applications": ["c442efda-6860-4299-8c13-0872745a065c"], "application": "c442efda-6860-4299-8c13-0872745a065c", "firmware_update": false}, "inference": {"supported_applications": ["32eee0f5-3db9-4660-8734-3cd9c8646cf8", "ba3ab86c-7e83-43c2-83aa-74f1b42f6838"], "application": "32eee0f5-3db9-4660-8734-3cd9c8646cf8", "firmware_update": false, "models": [{"model_name_reference": "tennis_activity_recognition_80x", "artifact_type": "json", "component_name": "lsm6dsv16x_mlc"}]}}]}, {"uuid": "abfac9a9-3319-4039-8a71-aa4e647c453b", "display_name": "Tennis Activity Recognition with SensorTile.box PRO and LSM6DSV320X sensor.", "description": "End-to-end system deployment for Tennis Activity Recognition use case on the SensorTile.box PRO using the LSM6DSV320X sensor.", "last_update_time": null, "last_deploy_result": null, "cloud_params": {"type": "azure_iotc", "app_url": null}, "gateway": [{"device_id": "gateway_0", "display_name": "gateway_0", "gateway_id": null, "description": "Gateway device at position 0.", "application": "2e3d92ca-c14a-4e9b-b270-50101a6151f9", "wifi_mode": "off"}], "leaf": [{"device_id": "leaf_0", "display_name": "leaf_0", "gateway_id": "gateway_0", "description": "Leaf device at position 0.", "datalogging": {"supported_applications": ["c442efda-6860-4299-8c13-0872745a065c"], "application": "c442efda-6860-4299-8c13-0872745a065c", "firmware_update": false}, "inference": {"supported_applications": ["32eee0f5-3db9-4660-8734-3cd9c8646cf8", "ba3ab86c-7e83-43c2-83aa-74f1b42f6838"], "application": "32eee0f5-3db9-4660-8734-3cd9c8646cf8", "firmware_update": false, "models": [{"model_name_reference": "tennis_activity_recognition_320x", "artifact_type": "json", "component_name": "lsm6dsv16x_mlc"}]}}]}]}

=== dabralhd/experimental/staiotcraft-json-analysis/processed_schema_workspace/ai_1828.json
{
    "$schema": "/data/artifacts/.assets/schemas/ai_main_schema.json",
    "schema_version": "v10",
    "ai_project_name": "test-project-111",
    "display_name": "Smart Asset Tracking",
    "description": "Classification of package conditions using the MLC to detect stationary orientation (upright or not) or moving and shaking states.\n\nWith this example, you can individually track the state of a physical item, such as a package, to monitor whether it is moving or being shaken too harshly, and whether it is still upright or not. Classification is very fast and will detect even brief events. You can also clone and retrain the model to adapt its classes to your use case, for example by tailoring the 'shaken' class to particularly strong motion or, on the contrary, by making it more sensitive for fragile items.\nTo use this example, simply position the board on top of the item, ensuring it is secured firmly. If you wish to avoid using a USB cable, you can also track it wirelessly from the ST AIoT Craft mobile app.",
    "type": "industrial",
    "uuid": "b6fc78ac-73de-4493-9ba6-f51c21d84208",
    "version": "1.0.0",
    "creation_time": "2025-08-20 10:06:31.504549",
    "last_update_time": "2025-08-20 10:06:31.504549",
    "models": [],
    "applications": [
        {
            "uuid": "04ee195d-0528-422c-9825-5cb6b6b096a7",
            "type": "gateway",
            "device_template_uri": "/e2e_systems/gateway/dtmi/appconfig/gateway/MLC_Gateway-7.expanded.json",
            "device_template_id": "dtmi:appconfig:gateway:MLC_Gateway;7",
            "device_manifest_uri": "/e2e_systems/gateway/dtmi/appconfig/gateway/MLC_Gateway-7.2.manifest.arm64v8.json",
            "image_uri": "/e2e_systems/gateway/images/raspberrypi/staiotcraft_rpi_gateway_1_4_0.img.gz",
            "module_id": "edgeMLC"
        },
        {
            "uuid": "59b0ca44-d85b-497d-812f-2cec1832f998",
            "type": "datalogging",
            "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/FP_SNS_DATALOG2_Datalog2-7.expanded.json",
            "device_template_id": "dtmi:appconfig:steval_mkboxpro:FP_SNS_DATALOG2_Datalog2;7",
            "binary_uri": "/bluestsdkv2/bin/steval-mkboxpro/FP-SNS-DATALOG2_Datalog2_3_1_0.bin",
            "binary_id": 381,
            "protocol": 2
        },
        {
            "uuid": "51f18268-b6a2-4488-a392-ff16b9549d9c",
            "type": "inference",
            "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/FP_SNS_STAIOTCFT_AI_Inertial-1.expanded.json",
            "device_template_id": "dtmi:appconfig:steval_mkboxpro:FP_SNS_STAIOTCFT_AI_Inertial;1",
            "binary_uri": "/usb/bin/steval-mkboxpro/FP-SNS-STAIOTCFT_AI_Inertial_AssetTrackingOnMLC_1_0_0.bin",
            "binary_id": 418,
            "protocol": 1
        }
    ],
    "deployments": [
        {
            "uuid": "a56f1c2a-db8b-4e19-9915-789a019893fa",
            "display_name": "Smart Asset Tracking end-to-end system with SensorTile.box PRO.",
            "description": "End-to-end system deployment for Smart Asset Tracking scenario.",
            "last_update_time": null,
            "last_deploy_result": null,
            "cloud_params": {
                "type": "azure_iotc",
                "app_url": null
            },
            "gateway": [
                {
                    "device_id": "gateway_0",
                    "display_name": "gateway_0",
                    "gateway_id": null,
                    "description": "Gateway device at position 0.",
                    "application": "04ee195d-0528-422c-9825-5cb6b6b096a7",
                    "wifi_mode": "off"
                }
            ],
            "leaf": [
                {
                    "device_id": "leaf_0",
                    "display_name": "leaf_0",
                    "gateway_id": "gateway_0",
                    "description": "Leaf device at position 0.",
                    "datalogging": {
                        "application": "59b0ca44-d85b-497d-812f-2cec1832f998",
                        "firmware_update": false
                    },
                    "inference": {
                        "application": "51f18268-b6a2-4488-a392-ff16b9549d9c",
                        "firmware_update": false,
                        "models": [
                            {
                                "model_name_reference": "smart_asset_tracking",
                                "artifact_type": "json",
                                "component_name": "lsm6dsv16x_mlc"
                            }
                        ]
                    }
                }
            ]
        }
    ],
    "project_owner_uuid": "334c65a5-1495-453a-a6de-4d384a781000"
}

=== dabralhd/experimental/staiotcraft-json-analysis/dev_cluster_projects_ai_json_files/ai_104.json
{"$schema": "/data/artifacts/.assets/schemas/ai_main_schema.json", "schema_version": "v11", "ai_project_name": "project_name_713720", "display_name": "Head Gestures", "description": "Classification of head gestures such as other, nod and shake using the MLC.\n\nWith this example, you can recognize head gestures such as nodding, shaking, and other general head movements, for applications that might involve safety helmets, VR headsets, and other forms of gear worn on the head. Since recognition can be position-dependent, you can clone this project, collect new data and retrain the model to fit it to your use case. To use this example, ensure that the board is placed firmly above the user's right ear vertically, with the USB port facing down toward the ear, and the LEDs and logos facing outward.", "type": "entertainment", "uuid": "a2021f34-78f1-46c5-9f8d-8182796cb682", "version": "1.0.0", "creation_time": "2026-01-21 09:18:36.171710", "last_update_time": "2026-01-21 09:18:36.171710", "project_owner_uuid": "90ab4947-c200-4776-a316-d02c3041c4b8", "models": [{"uuid": "dcade001-bcfe-4786-a2ca-3e30c819fcbc", "name": "head_gestures", "description": "Model to recognize head gestures, with an Auto-ML based approach.", "creation_time": "2026-01-21 09:18:36.171722", "last_update_time": "2026-01-21 09:18:36.171724", "model_owner_uuid": "90ab4947-c200-4776-a316-d02c3041c4b8", "metadata": {"type": "classifier", "classes": ["other", "nod", "shake"]}, "dataset": {"dataset_id": "01kffxj7xh8ct089qh9f5b7nhv", "name": "head_gestures"}, "target": {"type": "mlc", "component": "lsm6dsv16x", "device": "steval-mkboxpro"}, "data_sufficiency": {"creation_time": null, "last_update_time": null, "runtime": {"type": "job", "jobs": [{"name": "mlctools-ds-job", "version": null, "template_id": null}]}, "configuration": null, "artifacts": ["activities_training.json", "counts.json", "feat_names.json", "kmeans_cluster_labels.json", "lda.onnx", "my_kmeans.json", "my_tree.onnx", "window_size_odr_channels.json"], "reports": []}, "training": {"creation_time": null, "last_update_time": null, "runtime": {"type": "job", "jobs": [{"name": "mlctools-job", "version": null, "template_id": null}]}, "configuration": "configuration.json", "artifacts": ["lsm6dsv16x_mlc.json", "lsm6dsv16x_mlc.h"], "reports": ["report.json"]}, "codegen": null, "building": null}], "applications": [{"uuid": "73e81c9b-538f-4620-8877-11dec8dca191", "type": "gateway", "device_template_uri": "/e2e_systems/gateway/dtmi/appconfig/gateway/MLC_Gateway-8.expanded.json", "device_template_id": "dtmi:appconfig:gateway:MLC_Gateway;8", "device_manifest_uri": "/e2e_systems/gateway/dtmi/appconfig/gateway/MLC_Gateway-8.1.manifest.arm64v8.json", "image_uri": "/e2e_systems/gateway/images/raspberrypi/staiotcraft_rpi_gateway_1_5_0.img.gz", "module_id": "edgeMLC"}, {"uuid": "87a68d47-d83d-4f1e-8d2e-7dffa6851ce9", "type": "datalogging", "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/FP_SNS_DATALOG2_Datalog2-7.expanded.json", "device_template_id": "dtmi:appconfig:steval_mkboxpro:FP_SNS_DATALOG2_Datalog2;7", "binary_uri": "/bluestsdkv2/bin/steval-mkboxpro/FP-SNS-DATALOG2_Datalog2_3_1_0.bin", "binary_id": 381, "protocol": 2}, {"uuid": "d34aee97-ff7a-4beb-851a-f59fb6ddae8c", "type": "inference", "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/FP_SNS_STAIOTCFT_AI_Inertial-1.expanded.json", "device_template_id": "dtmi:appconfig:steval_mkboxpro:FP_SNS_STAIOTCFT_AI_Inertial;1", "binary_uri": "/usb/bin/steval-mkboxpro/FP-SNS-STAIOTCFT_AI_Inertial_AssetTrackingOnMLC_1_0_0.bin", "binary_id": 418, "protocol": 1}, {"uuid": "e1784c5e-ee13-4dc5-90d6-f93ae05c7d8a", "type": "inference", "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/AI_SSM-1.expanded.json", "device_template_id": "dtmi:appconfig:steval_mkboxpro:AI_SSM;1", "binary_uri": "/bluestsdkv2/bin/steval-mkboxpro/AI-SSM_1_0_0.bin", "binary_id": 438, "protocol": 0, "bluest_v3_payload": {"device_id": "0x0D", "fw_id": "0x25", "payload_id": "0x0001", "decoding_schema": [{"component": "lsm6dsv16x_mlc", "telemetry": "label_id", "type": "int8_t"}]}}], "deployments": [{"uuid": "85db134f-271a-41ef-adcd-65d0ce468121", "display_name": "Head Gestures with SensorTile.box PRO and LSM6DSV16X sensor.", "description": "End-to-end system deployment for Head Gestures use case on the SensorTile.box PRO using the LSM6DSV16X sensor.", "last_update_time": null, "last_deploy_result": null, "cloud_params": {"type": "azure_iotc", "app_url": null}, "gateway": [{"device_id": "gateway_0", "display_name": "gateway_0", "gateway_id": null, "description": "Gateway device at position 0.", "application": "1f90f38a-23ce-4a4e-9381-c89d206166b8", "wifi_mode": "off"}], "leaf": [{"device_id": "leaf_0", "display_name": "leaf_0", "gateway_id": "gateway_0", "description": "Leaf device at position 0.", "datalogging": {"supported_applications": ["15af1ac4-8144-45a7-b812-3fa89d051658"], "application": "15af1ac4-8144-45a7-b812-3fa89d051658", "firmware_update": false}, "inference": {"supported_applications": ["87526bc5-0e86-47e1-98e3-39d7f04e81f4", "34c9ce30-195c-4367-a2cd-481c2799a53d"], "application": "87526bc5-0e86-47e1-98e3-39d7f04e81f4", "firmware_update": false, "models": [{"model_name_reference": "head_gestures", "artifact_type": "json", "component_name": "lsm6dsv16x_mlc"}]}}]}]}

=== dabralhd/experimental/staiotcraft-json-analysis/ai-json-files/ai_193.json
{
    "$schema": "/data/artifacts/.assets/schemas/ai_main_schema.json",
    "schema_version": "v11",
    "ai_project_name": "test",
    "display_name": "Smart Asset Tracking",
    "description": "Classification of package conditions using the MLC to detect stationary orientation (upright or not) or moving and shaking states.\n\nWith this example, you can individually track the state of a physical item, such as a package, to monitor whether it is moving or being shaken too harshly, and whether it is still upright or not. Classification detects even brief events. You can clone and retrain the model to adapt classes to your use case, for example by tailoring the 'shaken' class to particularly strong motion or, conversely, by making it more sensitive for fragile items. To use this example, simply position the board on top of the item, ensuring it is secured firmly.",
    "type": "industrial",
    "uuid": "74301f2d-4366-4390-9f2c-a4a9360a69db",
    "version": "1.0.0",
    "creation_time": "2025-11-11 15:12:04.149033",
    "last_update_time": "2025-11-11 15:12:04.149033",
    "project_owner_uuid": "90ab4947-c200-4776-a316-d02c3041c4b8",
    "models": [
        {
            "uuid": "e7f3fbaf-bae7-47e4-aa57-0e56270bfb76",
            "name": "smart_asset_tracking",
            "description": "Model to recognize position and orientation of a tracked item, with an Auto-ML based approach.",
            "creation_time": "2025-11-11 15:12:04.149044",
            "last_update_time": "2025-11-11 15:12:04.149046",
            "model_owner_uuid": "90ab4947-c200-4776-a316-d02c3041c4b8",
            "metadata": {
                "type": "classifier",
                "classes": [
                    "stationary_upright",
                    "stationary_not_upright",
                    "motion",
                    "shaken"
                ]
            },
            "dataset": {
                "dataset_id": "01k9sqjpnzrknfmy6rpf36r25j",
                "name": "smart_asset_tracking"
            },
            "target": {
                "type": "mlc",
                "component": "lsm6dsv16x",
                "device": "steval-mkboxpro"
            },
            "data_sufficiency": {
                "creation_time": null,
                "last_update_time": null,
                "runtime": {
                    "type": "job",
                    "jobs": [
                        {
                            "name": "mlctools-ds-job",
                            "version": null,
                            "template_id": null
                        }
                    ]
                },
                "configuration": null,
                "artifacts": [
                    "activities_training.json",
                    "counts.json",
                    "feat_names.json",
                    "kmeans_cluster_labels.json",
                    "lda.onnx",
                    "my_kmeans.json",
                    "my_tree.onnx",
                    "window_size_odr_channels.json"
                ],
                "reports": []
            },
            "training": {
                "creation_time": null,
                "last_update_time": null,
                "runtime": {
                    "type": "job",
                    "jobs": [
                        {
                            "name": "mlctools-job",
                            "version": null,
                            "template_id": null
                        }
                    ]
                },
                "configuration": "configuration.json",
                "artifacts": [
                    "lsm6dsv16x_mlc.json",
                    "lsm6dsv16x_mlc.h"
                ],
                "reports": [
                    "report.json"
                ]
            },
            "codegen": null,
            "building": null
        }
    ],
    "applications": [
        {
            "uuid": "05574357-7953-4d04-8b70-a96984186c74",
            "type": "gateway",
            "device_template_uri": "/e2e_systems/gateway/dtmi/appconfig/gateway/MLC_Gateway-8.expanded.json",
            "device_template_id": "dtmi:appconfig:gateway:MLC_Gateway;8",
            "device_manifest_uri": "/e2e_systems/gateway/dtmi/appconfig/gateway/MLC_Gateway-8.1.manifest.arm64v8.json",
            "image_uri": "/e2e_systems/gateway/images/raspberrypi/staiotcraft_rpi_gateway_1_5_0.img.gz",
            "module_id": "edgeMLC"
        },
        {
            "uuid": "2820dce8-d9f3-4b44-8554-d1476d178b1e",
            "type": "datalogging",
            "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/FP_SNS_DATALOG2_Datalog2-7.expanded.json",
            "device_template_id": "dtmi:appconfig:steval_mkboxpro:FP_SNS_DATALOG2_Datalog2;7",
            "binary_uri": "/bluestsdkv2/bin/steval-mkboxpro/FP-SNS-DATALOG2_Datalog2_3_1_0.bin",
            "binary_id": 381,
            "protocol": 2
        },
        {
            "uuid": "bd21bcb6-6662-4229-83e1-39e1c8711773",
            "type": "inference",
            "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/FP_SNS_STAIOTCFT_AI_Inertial-1.expanded.json",
            "device_template_id": "dtmi:appconfig:steval_mkboxpro:FP_SNS_STAIOTCFT_AI_Inertial;1",
            "binary_uri": "/usb/bin/steval-mkboxpro/FP-SNS-STAIOTCFT_AI_Inertial_AssetTrackingOnMLC_1_0_0.bin",
            "binary_id": 418,
            "protocol": 1
        },
        {
            "uuid": "a2b9b93d-57c1-4b6e-90a8-70cc6d96c3dc",
            "type": "inference",
            "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/AI_SSM-1.expanded.json",
            "device_template_id": "dtmi:appconfig:steval_mkboxpro:AI_SSM;1",
            "binary_uri": "/bluestsdkv2/bin/steval-mkboxpro/AI-SSM_1_0_0.bin",
            "binary_id": 438,
            "protocol": 0,
            "bluest_v3_payload": {
                "device_id": "0x0D",
                "fw_id": "0x25",
                "payload_id": "0x0001",
                "decoding_schema": [
                    {
                        "component": "lsm6dsv16x_mlc",
                        "telemetry": "label_id",
                        "type": "int8_t"
                    }
                ]
            }
        }
    ],
    "deployments": [
        {
            "uuid": "c250d909-f485-4944-985d-bdf5bc233536",
            "display_name": "Smart Asset Tracking with SensorTile.box PRO and LSM6DSV16X sensor.",
            "description": "End-to-end system deployment for Smart Asset Tracking use case on the SensorTile.box PRO using the LSM6DSV16X sensor.",
            "last_update_time": null,
            "last_deploy_result": null,
            "cloud_params": {
                "type": "azure_iotc",
                "app_url": null
            },
            "gateway": [
                {
                    "device_id": "gateway_0",
                    "display_name": "gateway_0",
                    "gateway_id": null,
                    "description": "Gateway device at position 0.",
                    "application": "118107ef-15fa-4881-8aca-0285d3c1e2c3",
                    "wifi_mode": "off"
                }
            ],
            "leaf": [
                {
                    "device_id": "leaf_0",
                    "display_name": "leaf_0",
                    "gateway_id": "gateway_0",
                    "description": "Leaf device at position 0.",
                    "datalogging": {
                        "supported_applications": [
                            "8a5a3edd-3f0e-4081-95d7-91fbde8b4087"
                        ],
                        "application": "8a5a3edd-3f0e-4081-95d7-91fbde8b4087",
                        "firmware_update": false
                    },
                    "inference": {
                        "supported_applications": [
                            "28e63504-d01f-4cd7-91fe-e398c618c7cc",
                            "b360ee48-781c-4f8d-a3ad-79b326fa6460"
                        ],
                        "application": "28e63504-d01f-4cd7-91fe-e398c618c7cc",
                        "firmware_update": false,
                        "models": [
                            {
                                "model_name_reference": "smart_asset_tracking",
                                "artifact_type": "json",
                                "component_name": "lsm6dsv16x_mlc"
                            }
                        ]
                    }
                }
            ]
        }
    ]
}
