=== dabralhd/experimental/staiotcraft-json-analysis/clustered_ai-json-files/schema_group_14_86e55c69/detected_schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "uuid": {
      "type": "string"
    },
    "ai_project_name": {
      "type": "string"
    },
    "type": {
      "type": "null"
    },
    "display_name": {
      "type": "null"
    },
    "description": {
      "type": "null"
    },
    "version": {
      "type": "null"
    },
    "schema_version": {
      "type": "null"
    },
    "last_update_time": {
      "type": "string"
    },
    "creation_time": {
      "type": "string"
    },
    "project_owner_uuid": {
      "type": "string"
    },
    "models": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "uuid": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "dataset": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "dataset_id": {
                "type": "string"
              }
            },
            "required": [
              "dataset_id",
              "name"
            ]
          },
          "metadata": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "classes": {
                "type": "null"
              }
            },
            "required": [
              "classes",
              "type"
            ]
          },
          "target": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "component": {
                "type": "string"
              },
              "device": {
                "type": "string"
              }
            },
            "required": [
              "component",
              "device",
              "type"
            ]
          },
          "creation_time": {
            "type": "string"
          },
          "last_update_time": {
            "type": "string"
          },
          "model_owner_uuid": {
            "type": "string"
          }
        },
        "required": [
          "creation_time",
          "dataset",
          "last_update_time",
          "metadata",
          "model_owner_uuid",
          "name",
          "target",
          "uuid"
        ]
      }
    },
    "deployments": {
      "type": "array"
    },
    "applications": {
      "type": "array"
    }
  },
  "required": [
    "ai_project_name",
    "applications",
    "creation_time",
    "deployments",
    "description",
    "display_name",
    "last_update_time",
    "models",
    "project_owner_uuid",
    "schema_version",
    "type",
    "uuid",
    "version"
  ]
}

=== dabralhd/experimental/staiotcraft-json-analysis/ai-json-files/ai_92.json
{"$schema": "/data/artifacts/.assets/schemas/ai_main_schema.json", "schema_version": "v11", "ai_project_name": "tennisLOL", "display_name": "Tennis Activity Recognition", "description": "Classification of tennis shots using the MLC, including forehand, backhand, slice-forehand, slice-backhand, and serve strokes.\n\nThis example leverages both the accelerometer and the gyroscope sensors to better detect the movements. To use this example effectively, plug the DIL24 extension onto the board and place the board on the outside of the right wrist and secure it firmly. Make sure it is oriented in such a way that the two buttons are facing toward your shoulder, with the LEDs and logos visible and facing outward. In case you need a different placement on the wrist or want to add some more movements of your own, just clone the project into your workspace, collect a new dataset, and retrain the model.", "type": "entertainment", "uuid": "89925cca-93a8-4920-bc6a-3b39966f599b", "version": "1.0.0", "creation_time": "2026-01-20 16:00:41.966715", "last_update_time": "2026-01-20 16:00:41.966715", "project_owner_uuid": "90ab4947-c200-4776-a316-d02c3041c4b8", "models": [{"uuid": "755a7c3b-ceee-4932-8c68-f42a5e2b26cc", "name": "tennis_activity_recognition_80x", "description": "Model to recognize tennis shots, with an Auto-ML based approach.", "creation_time": "2026-01-20 16:00:41.966727", "last_update_time": "2026-01-20 16:00:41.966731", "model_owner_uuid": "90ab4947-c200-4776-a316-d02c3041c4b8", "metadata": {"type": "classifier", "classes": ["no_shot", "serve", "backhand_slice", "forehand_slice", "backhand", "forehand"]}, "dataset": {"dataset_id": "01kfe25fa6txhe3zwrjq3m25fb", "name": "tennis_activity_80x"}, "target": {"type": "mlc", "component": "lsm6dsv80x", "device": "steval-mkboxpro"}, "data_sufficiency": null, "training": {"creation_time": null, "last_update_time": null, "runtime": {"type": "job", "jobs": [{"name": "mlctools-job", "version": null, "template_id": null}]}, "configuration": "configuration.json", "artifacts": ["lsm6dsv80x_mlc.json", "lsm6dsv80x_mlc.h"], "reports": ["report.json"]}, "codegen": null, "building": null}, {"uuid": "b3a1b191-9b43-4b3a-8843-fcf91d53d1da", "name": "tennis_activity_recognition_320x", "description": "Model to recognize tennis shots, with an Auto-ML based approach.", "creation_time": "2026-01-20 16:00:41.966729", "last_update_time": "2026-01-20 16:00:41.966733", "model_owner_uuid": "90ab4947-c200-4776-a316-d02c3041c4b8", "metadata": {"type": "classifier", "classes": ["no_shot", "serve", "backhand_slice", "forehand_slice", "backhand", "forehand"]}, "dataset": {"dataset_id": "01kfe25gq0jrprmxwsr3dx1s8x", "name": "tennis_activity_320"}, "target": {"type": "mlc", "component": "lsm6dsv320x", "device": "steval-mkboxpro"}, "data_sufficiency": null, "training": {"creation_time": null, "last_update_time": null, "runtime": {"type": "job", "jobs": [{"name": "mlctools-job", "version": null, "template_id": null}]}, "configuration": "configuration.json", "artifacts": ["lsm6dsv320x_mlc.json", "lsm6dsv320x_mlc.h"], "reports": ["report.json"]}, "codegen": null, "building": null}], "applications": [{"uuid": "e5057fbd-f8ab-4a26-aad0-a6ed2d6e2187", "type": "gateway", "device_template_uri": "/e2e_systems/gateway/dtmi/appconfig/gateway/MLC_Gateway-8.expanded.json", "device_template_id": "dtmi:appconfig:gateway:MLC_Gateway;8", "device_manifest_uri": "/e2e_systems/gateway/dtmi/appconfig/gateway/MLC_Gateway-8.1.manifest.arm64v8.json", "image_uri": "/e2e_systems/gateway/images/raspberrypi/staiotcraft_rpi_gateway_1_5_0.img.gz", "module_id": "edgeMLC"}, {"uuid": "b80fca97-5b6a-4a01-86d5-fc165c62cce4", "type": "datalogging", "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/FP_SNS_DATALOG2_Datalog2-7.expanded.json", "device_template_id": "dtmi:appconfig:steval_mkboxpro:FP_SNS_DATALOG2_Datalog2;7", "binary_uri": "/bluestsdkv2/bin/steval-mkboxpro/FP-SNS-DATALOG2_Datalog2_3_1_0.bin", "binary_id": 381, "protocol": 2}, {"uuid": "3e4d22b7-68fb-421f-b677-0fef030d99a5", "type": "inference", "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/FP_SNS_STAIOTCFT_AI_Inertial-1.expanded.json", "device_template_id": "dtmi:appconfig:steval_mkboxpro:FP_SNS_STAIOTCFT_AI_Inertial;1", "binary_uri": "/usb/bin/steval-mkboxpro/FP-SNS-STAIOTCFT_AI_Inertial_AssetTrackingOnMLC_1_0_0.bin", "binary_id": 418, "protocol": 1}, {"uuid": "3f7e4ae2-6bd3-4fe9-811d-04ab899b9922", "type": "inference", "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/AI_SSM-1.expanded.json", "device_template_id": "dtmi:appconfig:steval_mkboxpro:AI_SSM;1", "binary_uri": "/bluestsdkv2/bin/steval-mkboxpro/AI-SSM_1_0_0.bin", "binary_id": 438, "protocol": 0, "bluest_v3_payload": {"device_id": "0x0D", "fw_id": "0x25", "payload_id": "0x0001", "description": "Environmental Monitor", "decoding_schema": [{"component": "lsm6dsv16x_mlc", "telemetry": "label_id", "type": "int8_t"}]}}], "deployments": [{"uuid": "416f7293-7db0-4282-96fe-01ef577bf064", "display_name": "Tennis Activity Recognition with SensorTile.box PRO and LSM6DSV80X sensor.", "description": "End-to-end system deployment for Tennis Activity Recognition use case on the SensorTile.box PRO using the LSM6DSV80X sensor.", "last_update_time": null, "last_deploy_result": null, "cloud_params": {"type": "azure_iotc", "app_url": null}, "gateway": [{"device_id": "gateway_0", "display_name": "gateway_0", "gateway_id": null, "description": "Gateway device at position 0.", "application": "cb6caf37-f2b5-4b4b-a792-ea24d3d9627f", "wifi_mode": "off"}], "leaf": [{"device_id": "leaf_0", "display_name": "leaf_0", "gateway_id": "gateway_0", "description": "Leaf device at position 0.", "datalogging": {"supported_applications": ["c3c13c0c-d026-48b2-bdee-aed468d73a16"], "application": "c3c13c0c-d026-48b2-bdee-aed468d73a16", "firmware_update": false}, "inference": {"supported_applications": ["27853bf2-e31f-41cb-98d7-991429f4ff05", "28ca13d0-f96b-4afa-9933-12432710e7d6"], "application": "27853bf2-e31f-41cb-98d7-991429f4ff05", "firmware_update": false, "models": [{"model_name_reference": "tennis_activity_recognition_80x", "artifact_type": "json", "component_name": "lsm6dsv16x_mlc"}]}}]}, {"uuid": "c5decbb3-f52b-4df3-baab-e5cff1ac2cc5", "display_name": "Tennis Activity Recognition with SensorTile.box PRO and LSM6DSV320X sensor.", "description": "End-to-end system deployment for Tennis Activity Recognition use case on the SensorTile.box PRO using the LSM6DSV320X sensor.", "last_update_time": null, "last_deploy_result": null, "cloud_params": {"type": "azure_iotc", "app_url": null}, "gateway": [{"device_id": "gateway_0", "display_name": "gateway_0", "gateway_id": null, "description": "Gateway device at position 0.", "application": "cb6caf37-f2b5-4b4b-a792-ea24d3d9627f", "wifi_mode": "off"}], "leaf": [{"device_id": "leaf_0", "display_name": "leaf_0", "gateway_id": "gateway_0", "description": "Leaf device at position 0.", "datalogging": {"supported_applications": ["c3c13c0c-d026-48b2-bdee-aed468d73a16"], "application": "c3c13c0c-d026-48b2-bdee-aed468d73a16", "firmware_update": false}, "inference": {"supported_applications": ["27853bf2-e31f-41cb-98d7-991429f4ff05", "28ca13d0-f96b-4afa-9933-12432710e7d6"], "application": "27853bf2-e31f-41cb-98d7-991429f4ff05", "firmware_update": false, "models": [{"model_name_reference": "tennis_activity_recognition_320x", "artifact_type": "json", "component_name": "lsm6dsv16x_mlc"}]}}]}]}

=== dabralhd/experimental/staiotcraft-json-analysis/processed_schema_workspace/ai_818.json
{
    "$schema": "/data/artifacts/.assets/schemas/ai_main_schema.json",
    "schema_version": "v12",
    "ai_project_name": "project_name_83481_shared",
    "display_name": "Head Gestures",
    "description": "Classification of head gestures such as other, nod and shake using the MLC.\n\nWith this example, you can recognize head gestures such as nodding, shaking, and other general head movements, for applications that might involve safety helmets, VR headsets, and other forms of gear worn on the head. Since recognition can be position-dependent, you can clone this project, collect new data and retrain the model to fit it to your use case. To use this example, ensure that the board is placed firmly above the user's right ear vertically, with the USB port facing down toward the ear, and the LEDs and logos facing outward.",
    "type": "entertainment",
    "uuid": "27a8606c-13ea-4b9d-8bdc-b78206b82a0f",
    "version": "1.0.0",
    "creation_time": "2026-05-11 13:30:04.539435",
    "last_update_time": "2026-05-11 13:30:04.539435",
    "project_owner_uuid": "7b9982b1-b4fe-455f-a776-ef65c061bee8",
    "models": [
        {
            "uuid": "9dc0410a-96ce-4b9c-8a33-015e686e273c",
            "name": "head_gestures_on_steval_mkboxpro",
            "description": "Model to recognize head gestures, with an Auto-ML based approach.",
            "creation_time": "2026-05-11 13:30:04.539451",
            "last_update_time": "2026-05-11 13:30:04.539456",
            "model_owner_uuid": "7b9982b1-b4fe-455f-a776-ef65c061bee8",
            "metadata": {
                "type": "classifier",
                "classes": [
                    "other",
                    "nod",
                    "shake"
                ]
            },
            "dataset": {
                "dataset_id": "01krbkp1f0dfpx5p6wqbk8cd14",
                "name": "head_gestures_on_steval_mkboxpro"
            },
            "target": {
                "type": "mlc",
                "component": "lsm6dsv16x",
                "device": "steval-mkboxpro"
            },
            "data_sufficiency": {
                "creation_time": null,
                "last_update_time": null,
                "runtime": {
                    "type": "job",
                    "jobs": [
                        {
                            "name": "mlctools-ds-job",
                            "version": null,
                            "template_id": null
                        }
                    ]
                },
                "configuration": null,
                "artifacts": [
                    "activities_training.json",
                    "counts.json",
                    "feat_names.json",
                    "kmeans_cluster_labels.json",
                    "lda.onnx",
                    "my_kmeans.json",
                    "my_tree.onnx",
                    "window_size_odr_channels.json"
                ],
                "reports": []
            },
            "training": {
                "creation_time": null,
                "last_update_time": null,
                "runtime": {
                    "type": "job",
                    "jobs": [
                        {
                            "name": "mlctools-job",
                            "version": null,
                            "template_id": null
                        }
                    ]
                },
                "configuration": "configuration.json",
                "artifacts": [
                    "lsm6dsv16x_mlc.json",
                    "lsm6dsv16x_mlc.h"
                ],
                "reports": [
                    "report.json"
                ]
            },
            "codegen": null,
            "building": null
        }
    ],
    "applications": [
        {
            "uuid": "b4bbb461-2b84-465a-bcb8-a1b401c1576a",
            "type": "gateway",
            "device_template_uri": "/e2e_systems/gateway/dtmi/appconfig/gateway/MLC_Gateway-8.expanded.json",
            "device_template_id": "dtmi:appconfig:gateway:MLC_Gateway;8",
            "device_manifest_uri": "/e2e_systems/gateway/dtmi/appconfig/gateway/MLC_Gateway-8.1.manifest.arm64v8.json",
            "image_uri": "/e2e_systems/gateway/images/raspberrypi/staiotcraft_rpi_gateway_1_5_0.img.gz",
            "module_id": "edgeMLC"
        },
        {
            "uuid": "9cb6b114-ccb1-420f-bcc7-41b6085892fc",
            "type": "datalogging",
            "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/FP_SNS_DATALOG2_Datalog2-8.expanded.json",
            "device_template_id": "dtmi:appconfig:steval_mkboxpro:FP_SNS_DATALOG2_Datalog2;8",
            "binary_uri": "/usb/bin/steval-mkboxpro/FP-SNS-DATALOG2_Datalog2_3_2_0.bin",
            "binary_id": 451,
            "protocol": 2
        },
        {
            "uuid": "1674b250-8c15-4409-90bf-6769a7a0b32f",
            "type": "datalogging",
            "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/STAIOTCRAFT_SDATALOG-1.expanded.json",
            "device_template_id": "dtmi:appconfig:steval_mkboxpro:STAIOTCRAFT_SDATALOG;1",
            "binary_uri": "/usb/bin/steval-mkboxpro/STAIOTCRAFT_SDATALOG_1_0_0.bin",
            "binary_id": 517,
            "protocol": 2
        },
        {
            "uuid": "77c61b14-efdd-460d-946b-06049469066b",
            "type": "datalogging",
            "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/STAIOTCRAFT_SDATALOG_RUST-1.expanded.json",
            "device_template_id": "dtmi:appconfig:steval_mkboxpro:STAIOTCRAFT_SDATALOG_RUST;1",
            "binary_uri": "/usb/bin/steval-mkboxpro/STAIOTCRAFT_SDATALOG_RUST_1_0_0.bin",
            "binary_id": 516,
            "protocol": 2
        },
        {
            "uuid": "11a1db1e-3a44-44a7-a33c-3bf2795093ef",
            "type": "inference",
            "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/STAIOTCRAFT_AI_Inertial-1.expanded.json",
            "device_template_id": "dtmi:appconfig:steval_mkboxpro:STAIOTCRAFT_AI_Inertial;1",
            "binary_uri": "/usb/bin/steval-mkboxpro/STAIOTCRAFT_AI_Inertial_1_2_0.bin",
            "binary_id": 484,
            "protocol": 1
        },
        {
            "uuid": "390938ac-22b1-4623-aedf-08c05951228c",
            "type": "inference",
            "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/STAIOTCRAFT_AI_SSM-1.expanded.json",
            "device_template_id": "dtmi:appconfig:steval_mkboxpro:STAIOTCRAFT_AI_SSM;1",
            "binary_uri": "/bluestsdkv2/bin/steval-mkboxpro/STAIOTCRAFT_AI_SSM_1_0_0.bin",
            "binary_id": 529,
            "protocol": 0,
            "bluest_v3_payload": {
                "device_id": "0x0D",
                "fw_id": "0x29",
                "payload_id": "0x0001",
                "decoding_schema": [
                    {
                        "component": "lsm6dsv16x_mlc",
                        "telemetry": "label_id",
                        "type": "int8_t"
                    }
                ]
            }
        }
    ],
    "deployments": [
        {
            "uuid": "7eeac224-0d60-4198-b055-035f597b0c1d",
            "display_name": "Head Gestures with SensorTile.box PRO and LSM6DSV16X sensor.",
            "description": "End-to-end system deployment for Head Gestures use case on the SensorTile.box PRO using the LSM6DSV16X sensor.",
            "last_update_time": null,
            "last_deploy_result": null,
            "cloud_params": {
                "type": "azure_iotc",
                "app_url": null
            },
            "gateway": [
                {
                    "device_id": "gateway_0",
                    "display_name": "gateway_0",
                    "gateway_id": null,
                    "description": "Gateway device at position 0.",
                    "application": "2375848c-53bd-481d-9036-da9715fb2012",
                    "wifi_mode": "off"
                }
            ],
            "leaf": [
                {
                    "device_id": "leaf_0",
                    "display_name": "leaf_0",
                    "gateway_id": "gateway_0",
                    "description": "Leaf device at position 0.",
                    "datalogging": {
                        "supported_applications": [
                            "2e90ef11-64fc-4659-a1c4-8427e67d2300",
                            "eef3feea-1c93-4c87-8814-9cb53d9fb9e5"
                        ],
                        "application": "2e90ef11-64fc-4659-a1c4-8427e67d2300",
                        "firmware_update": false,
                        "models": [
                            {
                                "model_name_reference": "head_gestures_on_steval_mkboxpro"
                            }
                        ]
                    },
                    "inference": {
                        "supported_applications": [
                            "8bdfc9e5-602b-4803-a35a-b1e769837143",
                            "6d5cc65a-d8a4-4d61-8037-e518fd9e8932"
                        ],
                        "application": "8bdfc9e5-602b-4803-a35a-b1e769837143",
                        "firmware_update": false,
                        "models": [
                            {
                                "model_name_reference": "head_gestures_on_steval_mkboxpro",
                                "artifact_type": "json",
                                "component_name": "lsm6dsv16x_mlc"
                            }
                        ]
                    }
                }
            ]
        }
    ]
}

=== dabralhd/experimental/staiotcraft-json-analysis/ai-json-files/ai_1561.json
{"$schema": "/data/artifacts/.assets/schemas/ai_main_schema.json", "schema_version": "v11", "ai_project_name": "project_name_210917", "display_name": "Drilling Machine", "description": "Classification of drill actions using the MLC to detect idle, screw, drilling or percussive drilling states.\n\nThis system provides an example of classifying specific actions rather than simple vibrations, enabling the detection of the operating modes of a common household power drill: screwing, drilling, and percussive drilling, or being stationary. Since motion recognition can be very specific, you can clone this project to retrain it and tailor it to a different drill. To use this example, affix the board firmly to the top side of the drill. Keep in mind that vibrations may dislodge the board, and classification accuracy improves the more securely it is attached to the machine.", "type": "industrial", "uuid": "8b94a897-9ccd-4f31-8ae4-31c1784f2890", "version": "1.0.0", "creation_time": "2026-01-20 13:00:14.885113", "last_update_time": "2026-01-20 13:00:14.885113", "project_owner_uuid": "90ab4947-c200-4776-a316-d02c3041c4b8", "models": [{"uuid": "41d06976-6f5d-4554-9299-fc1a62f09fc9", "name": "drilling_machine", "description": "Model to monitor a drill, with an Auto-ML based approach.", "creation_time": "2026-01-20 13:00:14.885124", "last_update_time": "2026-01-20 13:00:14.885130", "model_owner_uuid": "90ab4947-c200-4776-a316-d02c3041c4b8", "metadata": {"type": "classifier", "classes": ["idle", "screwing", "drilling", "percussive_drilling"]}, "dataset": {"dataset_id": "01kfdqv4pn3gkjkefstyj2fvpn", "name": "drilling_machine"}, "target": {"type": "mlc", "component": "ism330dhcx", "device": "steval-stwinbx1"}, "data_sufficiency": {"creation_time": null, "last_update_time": null, "runtime": {"type": "job", "jobs": [{"name": "mlctools-ds-job", "version": null, "template_id": null}]}, "configuration": null, "artifacts": ["activities_training.json", "counts.json", "feat_names.json", "kmeans_cluster_labels.json", "lda.onnx", "my_kmeans.json", "my_tree.onnx", "window_size_odr_channels.json"], "reports": []}, "training": {"creation_time": null, "last_update_time": null, "runtime": {"type": "job", "jobs": [{"name": "mlctools-job", "version": null, "template_id": null}]}, "configuration": "configuration.json", "artifacts": ["ism330dhcx_mlc.json", "ism330dhcx_mlc.h"], "reports": ["report.json"]}, "codegen": null, "building": null}, {"uuid": "5f7a690e-8d8f-4f72-94fb-79631c9a1f10", "name": "drilling_machine_on_stwin", "description": "Model to monitor a drill, with an Auto-ML based approach.", "creation_time": "2026-01-20 13:00:14.885127", "last_update_time": "2026-01-20 13:00:14.885133", "model_owner_uuid": "90ab4947-c200-4776-a316-d02c3041c4b8", "metadata": {"type": "classifier", "classes": ["idle", "screwing", "drilling", "percussive_drilling"]}, "dataset": {"dataset_id": "01kfdqv63sez1q9d0gd3kh17ep", "name": "drilling_machine_on_stwin"}, "target": {"type": "mlc", "component": "ism330dhcx", "device": "steval-stwinkt1b"}, "data_sufficiency": {"creation_time": null, "last_update_time": null, "runtime": {"type": "job", "jobs": [{"name": "mlctools-ds-job", "version": null, "template_id": null}]}, "configuration": null, "artifacts": ["activities_training.json", "counts.json", "feat_names.json", "hnne.pkl", "kmeans_cluster_labels.json", "my_kmeans.json", "my_tree.onnx", "window_size_odr_channels.json"], "reports": []}, "training": {"creation_time": null, "last_update_time": null, "runtime": {"type": "job", "jobs": [{"name": "mlctools-job", "version": null, "template_id": null}]}, "configuration": "configuration.json", "artifacts": ["ism330dhcx_mlc.json", "ism330dhcx_mlc.h"], "reports": ["report.json"]}, "codegen": null, "building": null}], "applications": [{"uuid": "7a00cc99-d1d8-455d-a331-9d281c7d08fa", "type": "gateway", "device_template_uri": "/e2e_systems/gateway/dtmi/appconfig/gateway/MLC_Gateway-8.expanded.json", "device_template_id": "dtmi:appconfig:gateway:MLC_Gateway;8", "device_manifest_uri": "/e2e_systems/gateway/dtmi/appconfig/gateway/MLC_Gateway-8.1.manifest.arm64v8.json", "image_uri": "/e2e_systems/gateway/images/raspberrypi/staiotcraft_rpi_gateway_1_5_0.img.gz", "module_id": "edgeMLC"}, {"uuid": "c47c3a26-350c-4c95-9146-d7d1cd69b4df", "type": "datalogging", "device_template_uri": "/dtmi/appconfig/steval_stwinbx1/FP_SNS_DATALOG2_Datalog2-9.expanded.json", "device_template_id": "dtmi:appconfig:steval_stwinbx1:FP_SNS_DATALOG2_Datalog2;9", "binary_uri": "/bluestsdkv2/bin/steval-stwinbx1/FP-SNS-DATALOG2_Datalog2_3_1_0.bin", "binary_id": 379, "protocol": 2}, {"uuid": "17c90646-ed0e-460d-b6bb-d531c0e2a368", "type": "inference", "device_template_uri": "/dtmi/appconfig/steval_stwinbx1/FP_SNS_STAIOTCFT_AI_Inertial-1.expanded.json", "device_template_id": "dtmi:appconfig:steval_stwinbx1:FP_SNS_STAIOTCFT_AI_Inertial;1", "binary_uri": "/usb/bin/steval-stwinbx1/FP-SNS-STAIOTCFT_AI_Inertial_VibrationMonitoringOnMLC_1_0_0.bin", "binary_id": 424, "protocol": 1}, {"uuid": "e3760694-9e18-4977-8a8d-d21fcaf1c0ec", "type": "datalogging", "device_template_uri": "/dtmi/appconfig/steval_stwinkt1b/FP_SNS_DATALOG2_Datalog2-4.expanded.json", "device_template_id": "dtmi:appconfig:steval_stwinkt1b:FP_SNS_DATALOG2_Datalog2;4", "binary_uri": "/bluestsdkv2/bin/steval-stwinkt1b/FP-SNS-DATALOG2_Datalog2_3_1_0.bin", "binary_id": 380, "protocol": 2}, {"uuid": "7500c232-f332-4094-8a90-bef7bebc55ef", "type": "inference", "device_template_uri": "/dtmi/appconfig/steval_stwinkt1b/FP_SNS_STAIOTCFT_AI_Inertial-1.expanded.json", "device_template_id": "dtmi:appconfig:steval_stwinkt1b:FP_SNS_STAIOTCFT_AI_Inertial;1", "binary_uri": "/usb/bin/steval-stwinkt1b/FP-SNS-STAIOTCFT_AI_Inertial_VibrationMonitoringOnMLC_1_0_0.bin", "binary_id": 426, "protocol": 1}], "deployments": [{"uuid": "287587bf-86ce-4242-bf1e-999f0f02b31b", "display_name": "Drilling Machine monitoring with STWIN.box and ISM330DHCX sensor.", "description": "End-to-end system deployment for Drilling Machine monitoring use case on the STWIN.box using the ISM330DHCX sensor.", "last_update_time": null, "last_deploy_result": null, "cloud_params": {"type": "azure_iotc", "app_url": null}, "gateway": [{"device_id": "gateway_0", "display_name": "gateway_0", "gateway_id": null, "description": "Gateway device at position 0.", "application": "38955195-ff61-410a-9014-770b4e24dcf7", "wifi_mode": "off"}], "leaf": [{"device_id": "leaf_0", "display_name": "leaf_0", "gateway_id": "gateway_0", "description": "Leaf device at position 0.", "datalogging": {"supported_applications": ["6bcc1fd7-11d4-4f77-95fb-d124ce83ee41"], "application": "6bcc1fd7-11d4-4f77-95fb-d124ce83ee41", "firmware_update": false}, "inference": {"supported_applications": ["dbec9cb6-7111-416a-a143-b98ae35a73bd"], "application": "dbec9cb6-7111-416a-a143-b98ae35a73bd", "firmware_update": false, "models": [{"model_name_reference": "drilling_machine", "artifact_type": "json", "component_name": "ism330dhcx_mlc"}]}}]}, {"uuid": "c21e112d-7ca0-4f5d-b405-229d0ba8326a", "display_name": "Drilling Machine monitoring with STWIN and ISM330DHCX sensor.", "description": "End-to-end system deployment for Drilling Machine monitoring use case on the STWIN using the ISM330DHCX sensor.", "last_update_time": null, "last_deploy_result": null, "cloud_params": {"type": "azure_iotc", "app_url": null}, "gateway": [{"device_id": "gateway_0", "display_name": "gateway_0", "gateway_id": null, "description": "Gateway device at position 0.", "application": "38955195-ff61-410a-9014-770b4e24dcf7", "wifi_mode": "off"}], "leaf": [{"device_id": "leaf_0", "display_name": "leaf_0", "gateway_id": "gateway_0", "description": "Leaf device at position 0.", "datalogging": {"supported_applications": ["efd5ae79-5905-4c08-b92c-9d21dcd5966a"], "application": "efd5ae79-5905-4c08-b92c-9d21dcd5966a", "firmware_update": false}, "inference": {"supported_applications": ["efd5ae79-5905-4c08-b92c-9d21dcd5966a"], "application": "ae4293c0-c698-4ab9-bd11-18aba7dad8b0", "firmware_update": false, "models": [{"model_name_reference": "drilling_machine_on_stwin", "artifact_type": "json", "component_name": "ism330dhcx_mlc"}]}}]}]}
