=== dabralhd/experimental/staiotcraft-json-analysis/consolidated_json_schemas/detected_schema_group_210_adbd08df.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "schema_version": {
      "type": "string"
    },
    "ai_project_name": {
      "type": "string"
    },
    "display_name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "type": {
      "type": "string"
    },
    "uuid": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "creation_time": {
      "type": "null"
    },
    "last_update_time": {
      "type": "null"
    },
    "project_owner_uuid": {
      "type": "null"
    },
    "models": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "uuid": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "creation_time": {
            "type": "null"
          },
          "last_update_time": {
            "type": "null"
          },
          "model_owner_uuid": {
            "type": "null"
          },
          "metadata": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "classes": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "classes",
              "type"
            ]
          },
          "dataset": {
            "type": "object",
            "properties": {
              "dataset_id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              }
            },
            "required": [
              "dataset_id",
              "name"
            ]
          },
          "target": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "component": {
                "type": "string"
              },
              "device": {
                "type": "string"
              }
            },
            "required": [
              "component",
              "device",
              "type"
            ]
          },
          "data_sufficiency": {
            "anyOf": [
              {
                "type": "null"
              },
              {
                "type": "object",
                "properties": {
                  "creation_time": {
                    "type": "null"
                  },
                  "last_update_time": {
                    "type": "null"
                  },
                  "runtime": {
                    "type": "object",
                    "properties": {
                      "type": {
                        "type": "string"
                      },
                      "jobs": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "name": {
                              "type": "string"
                            },
                            "version": {
                              "type": "null"
                            },
                            "template_id": {
                              "type": "null"
                            }
                          },
                          "required": [
                            "name",
                            "template_id",
                            "version"
                          ]
                        }
                      }
                    },
                    "required": [
                      "jobs",
                      "type"
                    ]
                  },
                  "configuration": {
                    "type": "null"
                  },
                  "artifacts": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "reports": {
                    "type": "array"
                  }
                },
                "required": [
                  "artifacts",
                  "configuration",
                  "creation_time",
                  "last_update_time",
                  "reports",
                  "runtime"
                ]
              }
            ]
          },
          "training": {
            "type": "object",
            "properties": {
              "creation_time": {
                "type": "null"
              },
              "last_update_time": {
                "type": "null"
              },
              "runtime": {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string"
                  },
                  "jobs": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "version": {
                          "type": "null"
                        },
                        "template_id": {
                          "type": "null"
                        }
                      },
                      "required": [
                        "name",
                        "template_id",
                        "version"
                      ]
                    }
                  }
                },
                "required": [
                  "jobs",
                  "type"
                ]
              },
              "configuration": {
                "type": "string"
              },
              "artifacts": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "reports": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "artifacts",
              "configuration",
              "creation_time",
              "last_update_time",
              "reports",
              "runtime"
            ]
          },
          "codegen": {
            "type": "null"
          },
          "building": {
            "type": "null"
          }
        },
        "required": [
          "building",
          "codegen",
          "creation_time",
          "data_sufficiency",
          "dataset",
          "description",
          "last_update_time",
          "metadata",
          "model_owner_uuid",
          "name",
          "target",
          "training",
          "uuid"
        ]
      }
    },
    "applications": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "uuid": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "device_template_uri": {
            "type": "string"
          },
          "device_template_id": {
            "type": "string"
          },
          "device_manifest_uri": {
            "type": "string"
          },
          "image_uri": {
            "type": "string"
          },
          "module_id": {
            "type": "string"
          },
          "binary_uri": {
            "type": "string"
          },
          "binary_id": {
            "type": "integer"
          },
          "protocol": {
            "type": "integer"
          },
          "bluest_v3_payload": {
            "type": "object",
            "properties": {
              "device_id": {
                "type": "string"
              },
              "fw_id": {
                "type": "string"
              },
              "payload_id": {
                "type": "string"
              },
              "decoding_schema": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "component": {
                      "type": "string"
                    },
                    "telemetry": {
                      "type": "string"
                    },
                    "type": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "component",
                    "telemetry",
                    "type"
                  ]
                }
              }
            },
            "required": [
              "decoding_schema",
              "device_id",
              "fw_id",
              "payload_id"
            ]
          }
        },
        "required": [
          "device_template_id",
          "device_template_uri",
          "type",
          "uuid"
        ]
      }
    },
    "deployments": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "uuid": {
            "type": "string"
          },
          "display_name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "last_update_time": {
            "type": "null"
          },
          "last_deploy_result": {
            "type": "null"
          },
          "cloud_params": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "app_url": {
                "type": "null"
              }
            },
            "required": [
              "app_url",
              "type"
            ]
          },
          "gateway": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "device_id": {
                  "type": "string"
                },
                "display_name": {
                  "type": "string"
                },
                "gateway_id": {
                  "type": "null"
                },
                "description": {
                  "type": "string"
                },
                "application": {
                  "type": "string"
                },
                "wifi_mode": {
                  "type": "string"
                }
              },
              "required": [
                "application",
                "description",
                "device_id",
                "display_name",
                "gateway_id",
                "wifi_mode"
              ]
            }
          },
          "leaf": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "device_id": {
                  "type": "string"
                },
                "display_name": {
                  "type": "string"
                },
                "gateway_id": {
                  "type": "string"
                },
                "description": {
                  "type": "string"
                },
                "datalogging": {
                  "type": "object",
                  "properties": {
                    "supported_applications": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "application": {
                      "type": "string"
                    },
                    "firmware_update": {
                      "type": "boolean"
                    },
                    "models": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "model_name_reference": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "model_name_reference"
                        ]
                      }
                    }
                  },
                  "required": [
                    "application",
                    "firmware_update",
                    "models",
                    "supported_applications"
                  ]
                },
                "inference": {
                  "type": "object",
                  "properties": {
                    "supported_applications": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      }
                    },
                    "application": {
                      "type": "string"
                    },
                    "firmware_update": {
                      "type": "boolean"
                    },
                    "models": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "model_name_reference": {
                            "type": "string"
                          },
                          "artifact_type": {
                            "type": "string"
                          },
                          "component_name": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "artifact_type",
                          "component_name",
                          "model_name_reference"
                        ]
                      }
                    }
                  },
                  "required": [
                    "application",
                    "firmware_update",
                    "models",
                    "supported_applications"
                  ]
                }
              },
              "required": [
                "datalogging",
                "description",
                "device_id",
                "display_name",
                "gateway_id"
              ]
            }
          }
        },
        "required": [
          "cloud_params",
          "description",
          "display_name",
          "gateway",
          "last_deploy_result",
          "last_update_time",
          "leaf",
          "uuid"
        ]
      }
    }
  },
  "required": [
    "$schema",
    "ai_project_name",
    "applications",
    "creation_time",
    "deployments",
    "description",
    "display_name",
    "last_update_time",
    "models",
    "project_owner_uuid",
    "schema_version",
    "type",
    "uuid",
    "version"
  ]
}

=== dabralhd/experimental/staiotcraft-json-analysis/clustered_ai-json-files/schema_group_65_73ec8622/ai_1806.json
{
    "$schema": "/data/artifacts/.assets/schemas/ai_main_schema.json",
    "schema_version": "v12",
    "ai_project_name": "get_started_joystick_monitoring_mlc",
    "display_name": "Joystick Project",
    "description": "Simple example of Joystick Project implemented using the accelerometer and gyroscope of the LSM6DSV16X sensor.\n\nWith this example, you can monitor the motion of the joystick. You can clone and retrain the model to adapt classes to your use case. To use this example, simply position the board on top of the item, ensuring it is secured firmly.",
    "type": "entertainment",
    "uuid": "uuid_to_replace_project",
    "version": "1.0.0",
    "creation_time": null,
    "last_update_time": null,
    "project_owner_uuid": null,
    "models": [
        {
            "uuid": "uuid_to_replace_model1",
            "name": "joystick_monitoring_on_steval_mkboxpro",
            "description": "Model to recognize motion of the joystick, with an Auto-ML based approach.",
            "creation_time": null,
            "last_update_time": null,
            "model_owner_uuid": null,
            "metadata": {
                "type": "classifier",
                "classes": [
                    "none",
                    "forward",
                    "left",
                    "right"
                ]
            },
            "dataset": {
                "dataset_id": "01kjaee2jx05jyn1ca4a46gwfk",
                "name": "joystick_monitoring_on_steval_mkboxpro"
            },
            "target": {
                "type": "mlc",
                "component": "lsm6dsv16x",
                "device": "steval-mkboxpro"
            },
            "data_sufficiency": null,
            "training": {
                "creation_time": null,
                "last_update_time": null,
                "runtime": {
                    "type": "job",
                    "jobs": [
                        {
                            "name": "mlctools-job",
                            "version": null,
                            "template_id": null
                        }
                    ]
                },
                "configuration": "configuration.json",
                "artifacts": [
                    "lsm6dsv16x_mlc.json",
                    "lsm6dsv16x_mlc.h"
                ],
                "reports": [
                    "report.json"
                ]
            },
            "codegen": null,
            "building": null
        }
    ],
    "applications": [
        {
            "uuid": "uuid_to_replace_application1",
            "type": "gateway",
            "device_template_uri": "/e2e_systems/gateway/dtmi/appconfig/gateway/MLC_Gateway-9.expanded.json",
            "device_template_id": "dtmi:appconfig:gateway:MLC_Gateway;9",
            "device_manifest_uri": "/e2e_systems/gateway/dtmi/appconfig/gateway/MLC_Gateway-9.1.RC1.manifest.arm64v8.json",
            "image_uri": "/e2e_systems/gateway/images/raspberrypi/staiotcraft_rpi_gateway_1_6_0_RC1.img.gz",
            "module_id": "edgeMLC"
        },
        {
            "uuid": "uuid_to_replace_application2",
            "type": "datalogging",
            "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/FP_SNS_DATALOG2_Datalog2-8.expanded.json",
            "device_template_id": "dtmi:appconfig:steval_mkboxpro:FP_SNS_DATALOG2_Datalog2;8",
            "binary_uri": "/usb/bin/steval-mkboxpro/FP-SNS-DATALOG2_Datalog2_3_2_0.bin",
            "binary_id": 451,
            "protocol": 2
        },
        {
            "uuid": "uuid_to_replace_application3",
            "type": "datalogging",
            "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/STAIOTCRAFT_SDATALOG-1.expanded.json",
            "device_template_id": "dtmi:appconfig:steval_mkboxpro:STAIOTCRAFT_SDATALOG;1",
            "binary_uri": "/usb/bin/steval-mkboxpro/STAIOTCRAFT_SDATALOG_1_0_0.bin",
            "binary_id": 517,
            "protocol": 2
        },    
        {
            "uuid": "uuid_to_replace_application4",
            "type": "datalogging",
            "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/STAIOTCRAFT_SDATALOG_RUST-1.expanded.json",
            "device_template_id": "dtmi:appconfig:steval_mkboxpro:STAIOTCRAFT_SDATALOG_RUST;1",
            "binary_uri": "/usb/bin/steval-mkboxpro/STAIOTCRAFT_SDATALOG_RUST_1_0_0.bin",
            "binary_id": 516,
            "protocol": 2
        },
        {
            "uuid": "uuid_to_replace_application5",
            "type": "inference",
            "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/STAIOTCRAFT_AI_Inertial-1.expanded.json",
            "device_template_id": "dtmi:appconfig:steval_mkboxpro:STAIOTCRAFT_AI_Inertial;1",
            "binary_uri": "/usb/bin/steval-mkboxpro/STAIOTCRAFT_AI_Inertial_1_2_0.bin",
            "binary_id": 484,
            "protocol": 1
        },
        {
            "uuid": "uuid_to_replace_application6",
            "type": "inference",
            "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/STAIOTCRAFT_AI_SSM-1.expanded.json",
            "device_template_id": "dtmi:appconfig:steval_mkboxpro:STAIOTCRAFT_AI_SSM;1",
            "binary_uri": "/bluestsdkv2/bin/steval-mkboxpro/STAIOTCRAFT_AI_SSM_1_0_0.bin",
            "binary_id": 529,
            "protocol": 0,
            "bluest_v3_payload": {
                "device_id": "0x0D",
                "fw_id": "0x29",
                "payload_id": "0x0001",
                "decoding_schema": [
                    {
                        "component": "lsm6dsv16x_mlc",
                        "telemetry": "label_id",
                        "type": "int8_t"
                    }
                ]
            }
        }
    ],
    "deployments": [
        {
            "uuid": "uuid_to_replace_deployment1",
            "display_name": "Joystick Project with SensorTile.box PRO and LSM6DSV16X sensor.",
            "description": "End-to-end system deployment for Joystick Project use case on the SensorTile.box PRO using the LSM6DSV16X sensor.",
            "last_update_time": null,
            "last_deploy_result": null,
            "cloud_params": {
                "type": "azure_iotc",
                "app_url": null
            },
            "gateway": [
                {
                    "device_id": "gateway_0",
                    "display_name": "gateway_0",
                    "gateway_id": null,
                    "description": "Gateway device at position 0.",
                    "application": "uuid_to_replace_application1",
                    "wifi_mode": "off"
                }
            ],
            "leaf": [
                {
                    "device_id": "leaf_0",
                    "display_name": "leaf_0",
                    "gateway_id": "gateway_0",
                    "description": "Leaf device at position 0.",
                    "datalogging": {
                        "supported_applications": [
                            "uuid_to_replace_application2"
                        ],
                        "application": "uuid_to_replace_application2",
                        "firmware_update": false,
                        "models": [
                            {
                                "model_name_reference": "joystick_monitoring_on_steval_mkboxpro"
                            }
                        ]
                    },
                    "inference": {
                        "supported_applications": [
                            "uuid_to_replace_application3",
                            "uuid_to_replace_application4"
                        ],
                        "application": "uuid_to_replace_application3",
                        "firmware_update": false,
                        "models": [
                            {
                                "model_name_reference": "joystick_monitoring_on_steval_mkboxpro",
                                "artifact_type": "json",
                                "component_name": "lsm6dsv16x_mlc"
                            }
                        ]
                    }
                }
            ]
        }
    ]
}
