=== dabralhd/experimental/staiotcraft-json-analysis/clustered_ai-json-files/schema_group_46_d5345969/detected_schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "uuid": {
      "type": "string"
    },
    "ai_project_name": {
      "type": "string"
    },
    "type": {
      "type": "null"
    },
    "display_name": {
      "type": "null"
    },
    "description": {
      "type": "string"
    },
    "version": {
      "type": "null"
    },
    "last_update_time": {
      "type": "string"
    },
    "creation_time": {
      "type": "string"
    },
    "project_owner_uuid": {
      "type": "string"
    },
    "models": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "uuid": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "dataset": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "dataset_id": {
                "type": "string"
              }
            },
            "required": [
              "dataset_id",
              "name"
            ]
          },
          "metadata": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "classes": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "classes",
              "type"
            ]
          },
          "target": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "component": {
                "type": "string"
              },
              "device": {
                "type": "string"
              }
            },
            "required": [
              "component",
              "device",
              "type"
            ]
          },
          "creation_time": {
            "type": "string"
          },
          "last_update_time": {
            "type": "string"
          },
          "model_owner_uuid": {
            "type": "string"
          },
          "training": {
            "type": "object",
            "properties": {
              "runtime": {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string"
                  },
                  "jobs": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "version": {
                          "type": "null"
                        },
                        "template_id": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "name",
                        "template_id",
                        "version"
                      ]
                    }
                  }
                },
                "required": [
                  "jobs",
                  "type"
                ]
              },
              "configuration": {
                "type": "string"
              },
              "reports": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "artifacts": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "last_update_time": {
                "type": "string"
              },
              "creation_time": {
                "type": "string"
              }
            },
            "required": [
              "artifacts",
              "configuration",
              "creation_time",
              "last_update_time",
              "reports",
              "runtime"
            ]
          }
        },
        "required": [
          "creation_time",
          "dataset",
          "last_update_time",
          "metadata",
          "model_owner_uuid",
          "name",
          "target",
          "uuid"
        ]
      }
    },
    "deployments": {
      "type": "array"
    },
    "applications": {
      "type": "array"
    }
  },
  "required": [
    "ai_project_name",
    "applications",
    "creation_time",
    "deployments",
    "description",
    "display_name",
    "last_update_time",
    "models",
    "project_owner_uuid",
    "type",
    "uuid",
    "version"
  ]
}

=== dabralhd/experimental/staiotcraft-json-analysis/dev_cluster_projects_ai_json_files/ai_901.json
{
    "uuid": "8eb1aa0d-6949-4bd1-8e1c-603a38050978",
    "ai_project_name": "QuickTest",
    "type": null,
    "display_name": null,
    "description": "",
    "version": null,
    "last_update_time": "2026-05-01 12:24:13.584798",
    "creation_time": "2026-05-01 12:24:11.974516",
    "project_owner_uuid": "72e55424-2031-70b8-e336-074935f590c2",
    "models": [
        {
            "uuid": "1d9bee5a-7de3-4195-b413-ac78dba14164",
            "name": "modelquick",
            "dataset": {
                "name": "datasettwo",
                "dataset_id": "01kqhqy5v5zrwfeg3xhn762qgs"
            },
            "metadata": {
                "type": "classifier",
                "classes": [
                    "class1",
                    "class2",
                    "class3"
                ]
            },
            "target": {
                "type": "mlc",
                "component": "lsm6dsv16x",
                "device": "steval-mkboxpro"
            },
            "creation_time": "2026-05-01 12:24:13.559012",
            "last_update_time": "2026-05-01 12:24:13.559020",
            "model_owner_uuid": "72e55424-2031-70b8-e336-074935f590c2"
        }
    ],
    "deployments": [],
    "applications": []
}

=== dabralhd/experimental/staiotcraft-json-analysis/dev_cluster_projects_ai_json_files/ai_428.json
{
    "uuid": "db36e775-cf17-4b62-aa88-140d996a6f40",
    "ai_project_name": "test_project",
    "type": null,
    "display_name": null,
    "description": "",
    "version": "1.0.0",
    "last_update_time": "2025-07-04 10:39:01.198950",
    "creation_time": "2025-07-04 10:39:01.198950",
    "project_owner_uuid": "cc5e60fa-3d75-4dda-b1cf-4ae88cbfe007",
    "models": [],
    "deployments": [],
    "applications": []
}

=== dabralhd/experimental/staiotcraft-json-analysis/dev_cluster_projects_ai_json_files/ai_498.json
{
    "uuid": "af769d6e-5d3c-4b4d-b320-ad1f88e49384",
    "ai_project_name": "TEst",
    "type": null,
    "display_name": null,
    "description": "",
    "version": null,
    "last_update_time": "2026-04-17 12:44:48.495193",
    "creation_time": "2026-04-17 12:44:47.277139",
    "project_owner_uuid": "b5feedda-585f-476d-9e40-52acec908605",
    "models": [
        {
            "uuid": "f1ded791-408a-4a22-a628-4006e42929b9",
            "name": "fdsdf",
            "dataset": {
                "name": "sdfasdf",
                "dataset_id": "01kpdqhtcc3vkbz0ra34hrn0fx"
            },
            "metadata": {
                "type": "classifier",
                "classes": [
                    "asdfasdf"
                ]
            },
            "target": {
                "type": "mlc",
                "component": "ism6hg256x",
                "device": "nucleo-stm32f401re"
            },
            "creation_time": "2026-04-17 12:44:48.465460",
            "last_update_time": "2026-04-17 12:44:48.465471",
            "model_owner_uuid": "b5feedda-585f-476d-9e40-52acec908605"
        }
    ],
    "deployments": [],
    "applications": []
}

=== dabralhd/experimental/staiotcraft-json-analysis/dev_cluster_projects_ai_json_files/ai_79.json
{
    "uuid": "f33f77e3-4f2a-4688-8920-225f65157925",
    "ai_project_name": "test-project-group-from-scratch_TC_3_p",
    "type": null,
    "display_name": null,
    "description": "My Project description",
    "version": "0.0.1",
    "last_update_time": "2025-07-31 06:36:04.542215",
    "creation_time": "2025-07-31 06:36:04.542215",
    "project_owner_uuid": "66f916f1-2386-4a92-80f0-13fb55329c79",
    "models": [],
    "deployments": [],
    "applications": []
}

=== dabralhd/experimental/staiotcraft-json-analysis/clustered_ai-json-files/schema_group_74_0eeac8f9/ai_1538.json
{
    "uuid": "c975dd72-37dc-4efa-b96b-e73274fe694d",
    "ai_project_name": "test_project_33",
    "type": null,
    "display_name": null,
    "description": "Project example description",
    "version": "1.0.0",
    "last_update_time": "2025-12-15 08:18:45.597121",
    "creation_time": "2025-12-15 08:18:45.597121",
    "project_owner_uuid": "66f916f1-2386-4a92-80f0-13fb55329c79",
    "models": [],
    "deployments": [
        {
            "uuid": "777389b5-57b4-4d93-ac37-497a53aa246b",
            "description": "End-to-end system deployment for Tennis Activity Recognition use case on the SensorTile.box PRO using the LSM6DSV80X sensor.",
            "display_name": "Tennis Activity Recognition",
            "cloud_params": {
                "type": "azure_iotc",
                "app_url": null
            },
            "last_update_time": "2025-12-15 08:18:49.629693",
            "last_deploy_result": "success",
            "leaf": [
                {
                    "gateway_id": "gateway_0",
                    "description": "Leaf device at position 0.",
                    "display_name": "leaf_0",
                    "device_id": "leaf_0",
                    "datalogging": {
                        "application": "2b05ee28-ec39-40ab-88b0-c0ad64ed7357",
                        "firmware_update": false,
                        "supported_applications": []
                    },
                    "inference": {
                        "application": "9d62c861-e66d-45a0-ae6b-0eab94cc8b4b",
                        "firmware_update": false,
                        "supported_applications": [],
                        "models": [
                            {
                                "artifact_type": "json",
                                "component_name": "lsm6dsv16x_mlc",
                                "model_name_reference": "tennis_activity_recognition_80x"
                            }
                        ]
                    }
                }
            ],
            "gateway": [
                {
                    "application": "be095058-9e05-471e-9970-20f0c9c4e963",
                    "description": "Gateway device at position 0.",
                    "display_name": "gateway_0",
                    "device_id": "gateway_0",
                    "wifi_mode": "off"
                }
            ]
        }
    ],
    "applications": [
        {
            "uuid": "be095058-9e05-471e-9970-20f0c9c4e963",
            "type": "gateway",
            "device_template_uri": "/e2e_systems/gateway/dtmi/appconfig/gateway/MLC_Gateway-8.expanded.json",
            "device_template_id": "dtmi:appconfig:gateway:MLC_Gateway;8",
            "device_manifest_uri": "/e2e_systems/gateway/dtmi/appconfig/gateway/MLC_Gateway-8.1.manifest.arm64v8.json",
            "image_uri": "/e2e_systems/gateway/images/raspberrypi/staiotcraft_rpi_gateway_1_5_0.img.gz",
            "module_id": "edgeMLC"
        },
        {
            "uuid": "2b05ee28-ec39-40ab-88b0-c0ad64ed7357",
            "type": "datalogging",
            "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/FP_SNS_DATALOG2_Datalog2-7.expanded.json",
            "device_template_id": "dtmi:appconfig:steval_mkboxpro:FP_SNS_DATALOG2_Datalog2;7",
            "binary_uri": "/bluestsdkv2/bin/steval-mkboxpro/FP-SNS-DATALOG2_Datalog2_3_1_0.bin",
            "binary_id": 381,
            "protocol": 2
        },
        {
            "uuid": "9d62c861-e66d-45a0-ae6b-0eab94cc8b4b",
            "type": "inference",
            "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/FP_SNS_STAIOTCFT_AI_Inertial-1.expanded.json",
            "device_template_id": "dtmi:appconfig:steval_mkboxpro:FP_SNS_STAIOTCFT_AI_Inertial;1",
            "binary_uri": "/usb/bin/steval-mkboxpro/FP-SNS-STAIOTCFT_AI_Inertial_AssetTrackingOnMLC_1_0_0.bin",
            "binary_id": 418,
            "protocol": 1
        },
        {
            "uuid": "17349799-1098-4aa5-a96a-46d1f294fb22",
            "type": "inference",
            "device_template_uri": "/dtmi/appconfig/steval_mkboxpro/AI_SSM-1.expanded.json",
            "device_template_id": "dtmi:appconfig:steval_mkboxpro:AI_SSM;1",
            "binary_uri": "/bluestsdkv2/bin/steval-mkboxpro/AI-SSM_1_0_0.bin",
            "binary_id": 438,
            "protocol": 0
        }
    ]
}

=== dabralhd/experimental/staiotcraft-json-analysis/dev_cluster_projects_ai_json_files/ai_410.json
{
    "uuid": "64f1af4e-2794-4c70-a68a-2d7c8add4193",
    "ai_project_name": "p",
    "type": null,
    "display_name": null,
    "description": "",
    "version": "1.0.0",
    "last_update_time": "2025-09-05 05:29:35.848811",
    "creation_time": "2025-09-05 05:29:35.848811",
    "project_owner_uuid": "f718fb0b-666a-4841-afd3-33dc9ea504ed",
    "models": [
        {
            "uuid": "6ba2c34f-a28f-4281-ae8d-f3faad2ff471",
            "name": "m",
            "dataset": {
                "name": "p",
                "dataset_id": "01k4c5m0hxb67cae8ttzwgz94d"
            },
            "metadata": {
                "type": "classifier",
                "classes": [
                    "stationary_upright",
                    "stationary_not_upright",
                    "motion",
                    "shaken"
                ]
            },
            "target": {
                "type": "mlc",
                "component": "lsm6dsv16x",
                "device": "steval-mkboxpro"
            },
            "creation_time": "2025-09-05 05:29:35.848823",
            "last_update_time": "2025-09-05 05:29:35.848825",
            "model_owner_uuid": "f718fb0b-666a-4841-afd3-33dc9ea504ed",
            "training": {
                "runtime": {
                    "type": "job",
                    "jobs": [
                        {
                            "name": "mlctools-job",
                            "version": null,
                            "template_id": "01J3QGW4RYFHA34N3Z3WPS97GH"
                        }
                    ]
                },
                "configuration": "configuration.json",
                "reports": [
                    "report.json"
                ],
                "artifacts": [
                    "lsm6dsv16x_mlc.json",
                    "lsm6dsv16x_mlc.h"
                ],
                "last_update_time": "2025-09-05 05:33:27.426677",
                "creation_time": "2025-09-05 05:33:27.426675"
            }
        }
    ],
    "deployments": [],
    "applications": []
}

=== dabralhd/experimental/staiotcraft-json-analysis/ai-json-files/ai_1775.json
{
    "uuid": "c43f14ac-61e7-461f-95e9-a714400e7534",
    "ai_project_name": "bug",
    "type": null,
    "display_name": null,
    "description": "",
    "version": null,
    "last_update_time": "2025-11-26 14:05:56.419917",
    "creation_time": "2025-11-26 14:05:55.218239",
    "project_owner_uuid": "ea66524a-2778-4966-a6ed-340abc5bc04b",
    "models": [
        {
            "uuid": "d6e62844-1035-4b05-9084-512ac5de198a",
            "name": "bugm",
            "dataset": {
                "name": "bugd",
                "dataset_id": "01kb07ra4ca6p81nrr7awz65n7"
            },
            "metadata": {
                "type": "classifier",
                "classes": [
                    "c",
                    "b"
                ]
            },
            "target": {
                "type": "mlc",
                "component": "ism330dhcx",
                "device": "steval-stwinkt1b"
            },
            "creation_time": "2025-11-26 14:05:56.393180",
            "last_update_time": "2025-11-26 14:05:56.393189",
            "model_owner_uuid": "ea66524a-2778-4966-a6ed-340abc5bc04b"
        }
    ],
    "deployments": [],
    "applications": []
}

=== dabralhd/experimental/staiotcraft-json-analysis/dev_cluster_projects_ai_json_files/ai_1713.json
{
    "uuid": "0c9e3d48-ff4c-4d67-8f27-b58c2c3c4c8f",
    "ai_project_name": "RobkitProject",
    "type": null,
    "display_name": null,
    "description": "",
    "version": null,
    "last_update_time": "2026-02-25 11:05:07.561709",
    "creation_time": "2026-02-25 11:05:06.186462",
    "project_owner_uuid": "26a9d3b9-5454-402d-ae7f-0b632bf4d26e",
    "models": [],
    "deployments": [],
    "applications": []
}
