=== dabralhd/experimental/staiotcraft-json-analysis/dev_cluster_json_shchemas/schema_group_3_4f7073a2/detected_schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "uuid": {
      "type": "string"
    },
    "ai_project_name": {
      "type": "string"
    },
    "type": {
      "type": "null"
    },
    "display_name": {
      "type": "null"
    },
    "description": {
      "type": "string"
    },
    "version": {
      "type": "null"
    },
    "last_update_time": {
      "type": "string"
    },
    "creation_time": {
      "type": "string"
    },
    "project_owner_uuid": {
      "type": "string"
    },
    "models": {
      "type": "array"
    },
    "deployments": {
      "type": "array"
    },
    "applications": {
      "type": "array"
    }
  },
  "required": [
    "ai_project_name",
    "applications",
    "creation_time",
    "deployments",
    "description",
    "display_name",
    "last_update_time",
    "models",
    "project_owner_uuid",
    "type",
    "uuid",
    "version"
  ]
}

=== dabralhd/experimental/staiotcraft-json-analysis/dev_cluster_projects_ai_json_files/ai_543.json
{
    "uuid": "bd8ab433-b2cd-497b-a4ec-3632cc333c42",
    "ai_project_name": "test_project_name_228004",
    "type": null,
    "display_name": null,
    "description": "Project example description",
    "version": "1.0.0",
    "last_update_time": "2025-09-05 12:49:44.557357",
    "creation_time": "2025-09-05 12:49:44.557357",
    "project_owner_uuid": "b5feedda-585f-476d-9e40-52acec908605",
    "models": [
        {
            "uuid": "0902e7e9-8f3b-4afd-a2a4-c0de1d67f7d7",
            "name": "model_example",
            "dataset": {
                "name": "01hy0rzc8jfhk5svwbb9reze42",
                "dataset_id": "01hy0rzc8jfhk5svwbb9reze42"
            },
            "metadata": {
                "type": "classifier",
                "classes": null
            },
            "target": {
                "type": "mlc",
                "component": "lsm6dsv16x",
                "device": "steval-mkboxpro"
            },
            "creation_time": "2025-09-05 12:49:45.951268",
            "last_update_time": "2025-09-05 12:49:45.951276",
            "model_owner_uuid": "b5feedda-585f-476d-9e40-52acec908605"
        }
    ],
    "deployments": [],
    "applications": []
}

=== dabralhd/experimental/staiotcraft-json-analysis/ai-json-files/ai_1666.json
{
    "uuid": "66d97948-187e-4d69-bf8a-1fa22e2a61b8",
    "ai_project_name": "test_project_name_221154",
    "type": null,
    "display_name": null,
    "description": "Project example description",
    "version": "1.0.0",
    "last_update_time": "2025-11-03 08:28:54.881435",
    "creation_time": "2025-11-03 08:28:54.881435",
    "project_owner_uuid": "b5feedda-585f-476d-9e40-52acec908605",
    "models": [
        {
            "uuid": "87f9a214-9afc-474d-9a41-d576f3fe3253",
            "name": "model_example",
            "dataset": {
                "name": "01hy0rzc8jfhk5svwbb9reze42",
                "dataset_id": "01hy0rzc8jfhk5svwbb9reze42"
            },
            "metadata": {
                "type": "classifier",
                "classes": null
            },
            "target": {
                "type": "mlc",
                "component": "lsm6dsv16x",
                "device": "steval-mkboxpro"
            },
            "creation_time": "2025-11-03 08:28:57.274398",
            "last_update_time": "2025-11-03 08:28:57.274407",
            "model_owner_uuid": "b5feedda-585f-476d-9e40-52acec908605"
        }
    ],
    "deployments": [],
    "applications": []
}
