=== dabralhd/experimental/staiotcraft-json-analysis/dev_cluster_json_shchemas/schema_group_3_4f7073a2/detected_schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "uuid": {
      "type": "string"
    },
    "ai_project_name": {
      "type": "string"
    },
    "type": {
      "type": "null"
    },
    "display_name": {
      "type": "null"
    },
    "description": {
      "type": "string"
    },
    "version": {
      "type": "null"
    },
    "last_update_time": {
      "type": "string"
    },
    "creation_time": {
      "type": "string"
    },
    "project_owner_uuid": {
      "type": "string"
    },
    "models": {
      "type": "array"
    },
    "deployments": {
      "type": "array"
    },
    "applications": {
      "type": "array"
    }
  },
  "required": [
    "ai_project_name",
    "applications",
    "creation_time",
    "deployments",
    "description",
    "display_name",
    "last_update_time",
    "models",
    "project_owner_uuid",
    "type",
    "uuid",
    "version"
  ]
}

=== dabralhd/experimental/staiotcraft-json-analysis/processed_schema_workspace/ai_1618.json
{
    "uuid": "be762a6a-e218-48a0-81cd-1c3b136b4f60",
    "ai_project_name": "test_project_name_634169",
    "type": null,
    "display_name": null,
    "description": "Project example description",
    "version": "1.0.0",
    "last_update_time": "2025-12-17 09:22:03.117110",
    "creation_time": "2025-12-17 09:22:03.117110",
    "project_owner_uuid": "b5feedda-585f-476d-9e40-52acec908605",
    "models": [
        {
            "uuid": "c96c0c4e-4996-4e6b-a3db-e06f1b09b085",
            "name": "model_example",
            "dataset": {
                "name": "01hy0rzc8jfhk5svwbb9reze42",
                "dataset_id": "01hy0rzc8jfhk5svwbb9reze42"
            },
            "metadata": {
                "type": "classifier",
                "classes": null
            },
            "target": {
                "type": "mlc",
                "component": "lsm6dsv16x",
                "device": "steval-mkboxpro"
            },
            "creation_time": "2025-12-17 09:22:04.461576",
            "last_update_time": "2025-12-17 09:22:04.461585",
            "model_owner_uuid": "b5feedda-585f-476d-9e40-52acec908605"
        }
    ],
    "deployments": [],
    "applications": []
}

=== dabralhd/experimental/staiotcraft-json-analysis/ai-json-files/ai_1691.json
{
    "uuid": "efd7077d-24f9-4975-a973-9862f7351901",
    "ai_project_name": "test_project_name_588879",
    "type": null,
    "display_name": null,
    "description": "Project example description",
    "version": "1.0.0",
    "last_update_time": "2025-09-05 13:03:10.745045",
    "creation_time": "2025-09-05 13:03:10.745045",
    "project_owner_uuid": "b5feedda-585f-476d-9e40-52acec908605",
    "models": [
        {
            "uuid": "d90ae00c-a012-4f2f-b5e3-3a842852e0ed",
            "name": "model_example",
            "dataset": {
                "name": "01hy0rzc8jfhk5svwbb9reze42",
                "dataset_id": "01hy0rzc8jfhk5svwbb9reze42"
            },
            "metadata": {
                "type": "classifier",
                "classes": null
            },
            "target": {
                "type": "mlc",
                "component": "lsm6dsv16x",
                "device": "steval-mkboxpro"
            },
            "creation_time": "2025-09-05 13:03:12.225130",
            "last_update_time": "2025-09-05 13:03:12.225136",
            "model_owner_uuid": "b5feedda-585f-476d-9e40-52acec908605"
        }
    ],
    "deployments": [],
    "applications": []
}

=== dabralhd/experimental/staiotcraft-json-analysis/ai-json-files/ai_1652.json
{
    "uuid": "9097a6c4-2ac8-4959-b544-24cd80fc59df",
    "ai_project_name": "test_project_name_584058",
    "type": null,
    "display_name": null,
    "description": "Project example description",
    "version": "1.0.0",
    "last_update_time": "2025-10-27 10:08:00.613680",
    "creation_time": "2025-10-27 10:08:00.613680",
    "project_owner_uuid": "b5feedda-585f-476d-9e40-52acec908605",
    "models": [
        {
            "uuid": "0c7c60f8-2077-477b-bdf5-07509aeee855",
            "name": "model_example",
            "dataset": {
                "name": "01hy0rzc8jfhk5svwbb9reze42",
                "dataset_id": "01hy0rzc8jfhk5svwbb9reze42"
            },
            "metadata": {
                "type": "classifier",
                "classes": null
            },
            "target": {
                "type": "mlc",
                "component": "lsm6dsv16x",
                "device": "steval-mkboxpro"
            },
            "creation_time": "2025-10-27 10:08:02.150426",
            "last_update_time": "2025-10-27 10:08:02.150435",
            "model_owner_uuid": "b5feedda-585f-476d-9e40-52acec908605"
        }
    ],
    "deployments": [],
    "applications": []
}

=== dabralhd/experimental/staiotcraft-json-analysis/dev_cluster_projects_ai_json_files/ai_629.json
{
    "uuid": "da68a1f8-7d33-4654-bc12-939bddc009ba",
    "ai_project_name": "test_project_name_942513",
    "type": null,
    "display_name": null,
    "description": "Project example description",
    "version": "1.0.0",
    "last_update_time": "2025-09-10 10:21:33.979215",
    "creation_time": "2025-09-10 10:21:33.979215",
    "project_owner_uuid": "b5feedda-585f-476d-9e40-52acec908605",
    "models": [
        {
            "uuid": "6967f298-3495-4dcd-a3ce-441b3246b163",
            "name": "model_example",
            "dataset": {
                "name": "01hy0rzc8jfhk5svwbb9reze42",
                "dataset_id": "01hy0rzc8jfhk5svwbb9reze42"
            },
            "metadata": {
                "type": "classifier",
                "classes": null
            },
            "target": {
                "type": "mlc",
                "component": "lsm6dsv16x",
                "device": "steval-mkboxpro"
            },
            "creation_time": "2025-09-10 10:21:35.501758",
            "last_update_time": "2025-09-10 10:21:35.501791",
            "model_owner_uuid": "b5feedda-585f-476d-9e40-52acec908605"
        }
    ],
    "deployments": [],
    "applications": []
}

=== dabralhd/experimental/staiotcraft-json-analysis/ai-json-files/ai_1703.json
{
    "uuid": "2403f8d1-929c-4fd1-be40-a82de55c4eea",
    "ai_project_name": "test_project_name_899645",
    "type": null,
    "display_name": null,
    "description": "Project example description",
    "version": "1.0.0",
    "last_update_time": "2025-10-30 13:01:44.111636",
    "creation_time": "2025-10-30 13:01:44.111636",
    "project_owner_uuid": "b5feedda-585f-476d-9e40-52acec908605",
    "models": [
        {
            "uuid": "967f6a24-d833-4647-b13b-c9510595634c",
            "name": "model_example",
            "dataset": {
                "name": "01hy0rzc8jfhk5svwbb9reze42",
                "dataset_id": "01hy0rzc8jfhk5svwbb9reze42"
            },
            "metadata": {
                "type": "classifier",
                "classes": null
            },
            "target": {
                "type": "mlc",
                "component": "lsm6dsv16x",
                "device": "steval-mkboxpro"
            },
            "creation_time": "2025-10-30 13:01:45.421715",
            "last_update_time": "2025-10-30 13:01:45.421723",
            "model_owner_uuid": "b5feedda-585f-476d-9e40-52acec908605"
        }
    ],
    "deployments": [],
    "applications": []
}

=== dabralhd/experimental/staiotcraft-json-analysis/ai-json-files/ai_1684.json
{
    "uuid": "e4c3255e-6b0d-441a-b2e7-ec24038e18e1",
    "ai_project_name": "test_project_name_639857",
    "type": null,
    "display_name": null,
    "description": "Project example description",
    "version": "1.0.0",
    "last_update_time": "2025-09-11 05:42:35.623491",
    "creation_time": "2025-09-11 05:42:35.623491",
    "project_owner_uuid": "b5feedda-585f-476d-9e40-52acec908605",
    "models": [
        {
            "uuid": "ddedf9d9-9d9f-44bf-a888-08945f28675a",
            "name": "model_example",
            "dataset": {
                "name": "01hy0rzc8jfhk5svwbb9reze42",
                "dataset_id": "01hy0rzc8jfhk5svwbb9reze42"
            },
            "metadata": {
                "type": "classifier",
                "classes": null
            },
            "target": {
                "type": "mlc",
                "component": "lsm6dsv16x",
                "device": "steval-mkboxpro"
            },
            "creation_time": "2025-09-11 05:42:36.932842",
            "last_update_time": "2025-09-11 05:42:36.932849",
            "model_owner_uuid": "b5feedda-585f-476d-9e40-52acec908605"
        }
    ],
    "deployments": [],
    "applications": []
}

=== dabralhd/experimental/staiotcraft-json-analysis/ai-json-files/ai_1632.json
{
    "uuid": "545b3727-f640-4321-a9c4-49d050d2bb90",
    "ai_project_name": "test_project_name_661174",
    "type": null,
    "display_name": null,
    "description": "Project example description",
    "version": "1.0.0",
    "last_update_time": "2025-09-11 05:42:43.177773",
    "creation_time": "2025-09-11 05:42:43.177773",
    "project_owner_uuid": "b5feedda-585f-476d-9e40-52acec908605",
    "models": [
        {
            "uuid": "89678ba8-e663-428a-82b1-1b38dd57c893",
            "name": "model_example",
            "dataset": {
                "name": "01hy0rzc8jfhk5svwbb9reze42",
                "dataset_id": "01hy0rzc8jfhk5svwbb9reze42"
            },
            "metadata": {
                "type": "classifier",
                "classes": null
            },
            "target": {
                "type": "mlc",
                "component": "lsm6dsv16x",
                "device": "steval-mkboxpro"
            },
            "creation_time": "2025-09-11 05:42:44.501797",
            "last_update_time": "2025-09-11 05:42:44.501805",
            "model_owner_uuid": "b5feedda-585f-476d-9e40-52acec908605"
        }
    ],
    "deployments": [],
    "applications": []
}

=== dabralhd/experimental/staiotcraft-json-analysis/dev_cluster_projects_ai_json_files/ai_631.json
{
    "uuid": "6419fe73-57ef-4cdb-889e-2fd2e18c3696",
    "ai_project_name": "test_project_name_944349",
    "type": null,
    "display_name": null,
    "description": "Project example description",
    "version": "1.0.0",
    "last_update_time": "2025-12-17 09:31:04.027269",
    "creation_time": "2025-12-17 09:31:04.027269",
    "project_owner_uuid": "b5feedda-585f-476d-9e40-52acec908605",
    "models": [
        {
            "uuid": "682ac5e8-369c-4130-8f92-da63b27e1b8d",
            "name": "model_example",
            "dataset": {
                "name": "01hy0rzc8jfhk5svwbb9reze42",
                "dataset_id": "01hy0rzc8jfhk5svwbb9reze42"
            },
            "metadata": {
                "type": "classifier",
                "classes": null
            },
            "target": {
                "type": "mlc",
                "component": "lsm6dsv16x",
                "device": "steval-mkboxpro"
            },
            "creation_time": "2025-12-17 09:31:05.414694",
            "last_update_time": "2025-12-17 09:31:05.414701",
            "model_owner_uuid": "b5feedda-585f-476d-9e40-52acec908605"
        }
    ],
    "deployments": [],
    "applications": []
}
