=== dabralhd/experimental/staiotcraft-json-analysis/clustered_ai-json-files/schema_group_122_445a6809/detected_schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "schema_version": {
      "type": "string"
    },
    "ai_project_name": {
      "type": "string"
    },
    "display_name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "uuid": {
      "type": "string"
    },
    "version": {
      "type": "string"
    },
    "creation_time": {
      "type": "null"
    },
    "last_update_time": {
      "type": "null"
    },
    "models": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "uuid": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "creation_time": {
            "type": "null"
          },
          "last_update_time": {
            "type": "null"
          },
          "metadata": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "classes": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "classes",
              "type"
            ]
          },
          "dataset": {
            "type": "object",
            "properties": {
              "dataset_id": {
                "type": "string"
              },
              "name": {
                "type": "string"
              }
            },
            "required": [
              "dataset_id",
              "name"
            ]
          },
          "target": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "component": {
                "type": "string"
              },
              "device": {
                "type": "string"
              }
            },
            "required": [
              "component",
              "device",
              "type"
            ]
          },
          "training": {
            "type": "object",
            "properties": {
              "creation_time": {
                "type": "null"
              },
              "last_update_time": {
                "type": "null"
              },
              "runtime": {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string"
                  },
                  "jobs": {
                    "type": "array"
                  }
                },
                "required": [
                  "jobs",
                  "type"
                ]
              },
              "configuration": {
                "type": "string"
              },
              "artifacts": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              },
              "reports": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            },
            "required": [
              "artifacts",
              "configuration",
              "reports",
              "runtime"
            ]
          },
          "codegen": {
            "type": "null"
          },
          "building": {
            "type": "null"
          }
        },
        "required": [
          "dataset",
          "metadata",
          "name",
          "target",
          "training",
          "uuid"
        ]
      }
    },
    "deployments": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "uuid": {
            "type": "string"
          },
          "display_name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "last_update_time": {
            "type": "null"
          },
          "last_deploy_result": {
            "type": "null"
          },
          "cloud_params": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string"
              },
              "app_url": {
                "type": "null"
              }
            },
            "required": [
              "app_url",
              "type"
            ]
          },
          "configuration": {
            "type": "object",
            "properties": {
              "leaf": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "device_id": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    },
                    "gateway_id": {
                      "type": "string"
                    },
                    "selected_model_name": {
                      "type": "string"
                    },
                    "models": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "name": {
                            "type": "string"
                          },
                          "datalogging": {
                            "type": "object",
                            "properties": {
                              "device_template_uri": {
                                "type": "string"
                              },
                              "device_template_id": {
                                "type": "string"
                              },
                              "protocol": {
                                "type": "integer"
                              },
                              "firmware_uri": {
                                "type": "string"
                              }
                            },
                            "required": [
                              "device_template_id",
                              "device_template_uri",
                              "firmware_uri",
                              "protocol"
                            ]
                          },
                          "inference": {
                            "type": "object",
                            "properties": {
                              "device_template_uri": {
                                "type": "string"
                              },
                              "device_template_id": {
                                "type": "string"
                              },
                              "protocol": {
                                "type": "integer"
                              },
                              "firmware_uri": {
                                "type": "string"
                              },
                              "ml_uri": {
                                "type": "string"
                              },
                              "firmware_update": {
                                "type": "boolean"
                              }
                            },
                            "required": [
                              "device_template_id",
                              "device_template_uri",
                              "firmware_update",
                              "firmware_uri",
                              "ml_uri",
                              "protocol"
                            ]
                          }
                        },
                        "required": [
                          "datalogging",
                          "inference",
                          "name"
                        ]
                      }
                    }
                  },
                  "required": [
                    "description",
                    "device_id",
                    "gateway_id",
                    "models",
                    "selected_model_name"
                  ]
                }
              },
              "gateway": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "device_id": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    },
                    "gateway_id": {
                      "type": "null"
                    },
                    "module_id": {
                      "type": "string"
                    },
                    "configuration_uri": {
                      "type": "string"
                    },
                    "device_manifest_uri": {
                      "type": "string"
                    },
                    "device_template_uri": {
                      "type": "string"
                    },
                    "device_template_id": {
                      "type": "string"
                    },
                    "wifi_mode": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "configuration_uri",
                    "description",
                    "device_id",
                    "device_manifest_uri",
                    "device_template_id",
                    "device_template_uri",
                    "gateway_id",
                    "module_id",
                    "wifi_mode"
                  ]
                }
              }
            },
            "required": [
              "gateway",
              "leaf"
            ]
          }
        },
        "required": [
          "cloud_params",
          "configuration",
          "description",
          "display_name",
          "last_deploy_result",
          "last_update_time",
          "uuid"
        ]
      }
    }
  },
  "required": [
    "$schema",
    "ai_project_name",
    "creation_time",
    "deployments",
    "description",
    "display_name",
    "last_update_time",
    "models",
    "schema_version",
    "uuid",
    "version"
  ]
}

=== dabralhd/experimental/staiotcraft-json-analysis/dev_cluster_projects_ai_json_files/ai_765.json
{
    "$schema": "/data/artifacts/.assets/schemas/ai_main_schema.json",
    "schema_version": "v9",
    "ai_project_name": "Project_name_240799",
    "display_name": "Asset Tracking",
    "description": "Get started project for asset tracking scenario run on the MLC sensor.",
    "uuid": "17a42331-fda5-4c47-be49-0cbc4f10e028",
    "version": "1.0.0",
    "creation_time": "2024-08-15 07:34:40.298546",
    "last_update_time": "2024-08-15 07:34:40.298546",
    "models": [
        {
            "uuid": "79a05e9b-bf7f-4501-aff8-e28add1596ad",
            "name": "asset_tracking",
            "description": "Model to recognize position and orientation of a tracked item, with an Auto-ML based approach.",
            "creation_time": "2024-08-15 07:34:40.298560",
            "last_update_time": "2024-08-15 07:34:40.298563",
            "metadata": {
                "type": "classifier",
                "classes": [
                    "stationary_upright",
                    "stationary_not_upright",
                    "motion",
                    "shaken"
                ]
            },
            "dataset": {
                "dataset_id": "01j5afbn66xe7ydq6s86qa6a9k",
                "name": "Dataset for the asset tracking get started project"
            },
            "target": {
                "type": "mlc",
                "component": "lsm6dsv16x",
                "device": "steval-mkboxpro"
            },
            "data-sufficiency": {
                "creation_time": null,
                "last_update_time": null,
                "runtime": {
                    "type": "job",
                    "jobs": [
                        {
                            "name": "mlctools-ds-job",
                            "version": null,
                            "template_id": null
                        }
                    ]
                },
                "configuration": null,
                "artifacts": [
                    "activities_training.json",
                    "counts.json",
                    "feat_names.json",
                    "hnne.pkl",
                    "kmeans_cluster_labels.json",
                    "my_kmeans.json",
                    "my_tree.onnx",
                    "my_tree.txt",
                    "shap.pkl",
                    "window_size_odr_channels.json"
                ],
                "reports": []
            },
            "training": {
                "creation_time": null,
                "last_update_time": null,
                "runtime": {
                    "type": "job",
                    "jobs": []
                },
                "configuration": "configuration.json",
                "artifacts": [
                    "lsm6dsv16x_mlc.ucf",
                    "lsm6dsv16x_mlc.h"
                ],
                "reports": [
                    "report.json"
                ]
            },
            "codegen": null,
            "building": null
        }
    ],
    "deployments": [
        {
            "uuid": "b3105309-7316-434e-8ed1-3b425800e76e",
            "display_name": "Asset Tracking end-to-end system.",
            "description": "End-to-end system deployment for Asset Tracking scenario.",
            "last_update_time": null,
            "last_deploy_result": null,
            "cloud_params": {
                "type": "azure_iotc",
                "app_url": null
            },
            "configuration": {
                "leaf": [
                    {
                        "device_id": "leaf_0",
                        "description": "Leaf device at position 0.",
                        "gateway_id": "gateway_0",
                        "selected_model_name": "asset_tracking",
                        "models": [
                            {
                                "name": "asset_tracking",
                                "datalogging": {
                                    "device_template_uri": "https://raw.githubusercontent.com/STMicroelectronics/appconfig/release/dtmi/appconfig/steval_mkboxpro/FP_SNS_DATALOG2_Datalog2-4.expanded.json",
                                    "device_template_id": "dtmi:appconfig:steval_mkboxpro:FP_SNS_DATALOG2_Datalog2;4",
                                    "protocol": 2,
                                    "firmware_uri": "https://raw.githubusercontent.com/STMicroelectronics/appconfig/release/bluestsdkv2/bin/steval-mkboxpro/FP-SNS-DATALOG2_Datalog2_2_1_1.bin"
                                },
                                "inference": {
                                    "device_template_uri": "e2e_system_deployment/leaf/steval_mkboxpro/asset_tracking_mlc-1.expanded.json",
                                    "device_template_id": "dtmi:vespucci:steval_mkboxpro:asset_tracking_mlc;1",
                                    "protocol": 1,
                                    "firmware_uri": "e2e_system_deployment/leaf/steval_mkboxpro/ai_inertial_steval_mkboxpro_mlc_release_1_0_0.bin",
                                    "ml_uri": "models/asset_tracking/training/lsm6dsv16x_mlc.ucf",
                                    "firmware_update": false
                                }
                            }
                        ]
                    }
                ],
                "gateway": [
                    {
                        "device_id": "gateway_0",
                        "description": "Gateway device at position 0.",
                        "gateway_id": null,
                        "module_id": "edgeMLC",
                        "configuration_uri": "e2e_system_deployment/gateway/vespucci_config.ini.template",
                        "device_manifest_uri": "e2e_system_deployment/gateway/mlc_gateway-2.manifest.json",
                        "device_template_uri": "e2e_system_deployment/gateway/mlc_gateway-2.expanded.json",
                        "device_template_id": "dtmi:vespucci:gateway:mlc_gateway;1",
                        "wifi_mode": "off"
                    }
                ]
            }
        }
    ]
}
